# Working with a sensor network that logs readings every hour. Reveive data in two separate shifts(morining and evening), each with 3 sensors.

In [1]:
import numpy as np 
morning = np.array([
    [22.1, 45.3, 0.91],
    [22.5, 46.1, 0.89],
    [23.0, 47.5, 0.87],
    [23.8, 48.2, 0.85],
    [24.1, 49.0, 0.84],
    [24.5, 49.8, 0.82]
])  # 6 hours × 3 sensors

evening = np.array([
    [26.3, 55.1, 0.78],
    [25.9, 54.3, 0.80],
    [25.4, 53.0, 0.81],
    [24.8, 51.7, 0.83],
    [24.2, 50.5, 0.84],
    [23.7, 49.2, 0.86]
])  # 6 hours × 3 sensors

In [ ]:
# Combine both shifts into a full 12-hours log.
fullShift=np.vstack([morning,evening])
print("Full Shift(12-hour) Sensor Readings:\n",fullShift)

Full Shift Sensor Readings:
 [[22.1  45.3   0.91]
 [22.5  46.1   0.89]
 [23.   47.5   0.87]
 [23.8  48.2   0.85]
 [24.1  49.    0.84]
 [24.5  49.8   0.82]
 [26.3  55.1   0.78]
 [25.9  54.3   0.8 ]
 [25.4  53.    0.81]
 [24.8  51.7   0.83]
 [24.2  50.5   0.84]
 [23.7  49.2   0.86]]


In [3]:
# Split the full log into 3 equal time blocks.
firstBlock,secondBlock,thirdBlock=np.vsplit(fullShift,3)
print("First time block log: \n",firstBlock)
print("Second time block log: \n",secondBlock)
print("Third time block log: \n",thirdBlock)

First time block log: 
 [[22.1  45.3   0.91]
 [22.5  46.1   0.89]
 [23.   47.5   0.87]
 [23.8  48.2   0.85]]
Second time block log: 
 [[24.1  49.    0.84]
 [24.5  49.8   0.82]
 [26.3  55.1   0.78]
 [25.9  54.3   0.8 ]]
Third time block log: 
 [[25.4  53.    0.81]
 [24.8  51.7   0.83]
 [24.2  50.5   0.84]
 [23.7  49.2   0.86]]


In [6]:
# For each block, compute the mean of each sensor.
Block1Mean=firstBlock.mean(axis=0)
Block2Mean=secondBlock.mean(axis=0)
Block3Mean=thirdBlock.mean(axis=0)

print("First Blocks' sensors mean: ",Block1Mean)
print("Second Blocks' sensors mean: ",Block2Mean)
print("Third Blocks' sensors mean: ",Block3Mean)


First Blocks' sensors mean:  [22.85  46.775  0.88 ]
Second Blocks' sensors mean:  [25.2  52.05  0.81]
Third Blocks' sensors mean:  [24.525 51.1    0.835]


In [7]:
# Stack the 3 mean rows into a summary array of shape(3,3) -> each row=one block's averages
summary_arr=np.vstack([Block1Mean,Block2Mean,Block3Mean])
print("The mean summary array : \n",summary_arr)

The mean summary array : 
 [[22.85  46.775  0.88 ]
 [25.2   52.05   0.81 ]
 [24.525 51.1    0.835]]


# Building a basic rain/test split for a small dataset. The dataset has 10 samples, each with 4 features:

In [8]:
np.random.seed(42)
data = np.random.randint(50, 100, size=(10, 4))
labels = np.array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0])

In [31]:
# Split data into 80% train and 20% test.
train,test=np.vsplit(data,[0,8]),np.vsplit(data,[8,9])
print(train)

[array([], shape=(0, 4), dtype=int32), array([[88, 78, 64, 92],
       [57, 70, 88, 68],
       [72, 60, 60, 73],
       [85, 89, 73, 52],
       [71, 51, 73, 93],
       [79, 87, 51, 70],
       [82, 61, 71, 93],
       [74, 98, 76, 91]], dtype=int32), array([[77, 65, 64, 96],
       [93, 52, 86, 56]], dtype=int32)]


# Real World Problem
   # Working at a retail company tracking weekly sales across 5 products      categories   over 4 weeeks. Data arrives in two parts: first 2 weeks and last 2 weeks.

In [ ]:
weeks_1_2 = np.array([
    [1200, 850,  300, 1750, 640],
    [1350, 920,  275, 1800, 710]
])

weeks_3_4 = np.array([
    [980,  870,  410, 1600, 780],
    [1100, 950,  390, 1900, 820]
])
category=["Electornics","Clothing","Stationary","Food","Sports"]

In [33]:
# Join both parts into a full monthly dataset.
fullMonth=np.vstack([weeks_1_2,weeks_3_4])
print("Overall Month Dataset: \n",fullMonth)

Overall Month Dataset: 
 [[1200  850  300 1750  640]
 [1350  920  275 1800  710]
 [ 980  870  410 1600  780]
 [1100  950  390 1900  820]]


In [34]:
# Split the dataset into individual weeks.
week1,week2,week3,week4=np.vsplit(fullMonth,4)
print("First week Datasets: ",week1)
print("Second week Datasets: ",week2)
print("Third week Datasets: ",week3)
print("Last week Datasets: ",week4)

First week Datasets:  [[1200  850  300 1750  640]]
Second week Datasets:  [[1350  920  275 1800  710]]
Third week Datasets:  [[ 980  870  410 1600  780]]
Last week Datasets:  [[1100  950  390 1900  820]]


In [44]:
# For each week, find the index of the best-selling and worst-selling category.
print("Week1: ")
print('-'*55)
print(f"Best selling category is {category[np.argmax(week1)]} with sale of {week1.max()}$")
print(f"Worst selling category is {category[np.argmin(week1)]} with sale of {week1.min()}$\n")

print("Week2:")
print('-'*55)
print(f"Best selling category of is {category[np.argmax(week2)]} with sale of {week2.max()}$")
print(f"Worst selling category of is {category[np.argmin(week2)]} with sale of {week2.min()}$\n")

print("Week3:")
print('-'*55)
print(f"Best selling category of is {category[np.argmax(week3)]} with sale of {week3.max()}$")
print(f"Worst selling category of is {category[np.argmin(week3)]} with sale of {week3.min()}$\n")

print("Week4:")
print('-'*55)
print(f"Best selling category of is {category[np.argmax(week4)]} with sale of {week4.max()}$")
print(f"Worst selling category of is {category[np.argmin(week4)]} with sale of {week4.min()}$\n")

Week1: 
-------------------------------------------------------
Best selling category is Food with sale of 1750$
Worst selling category is Stationary with sale of 300$

Week2:
-------------------------------------------------------
Best selling category of is Food with sale of 1800$
Worst selling category of is Stationary with sale of 275$

Week3:
-------------------------------------------------------
Best selling category of is Food with sale of 1600$
Worst selling category of is Stationary with sale of 410$

Week4:
-------------------------------------------------------
Best selling category of is Food with sale of 1900$
Worst selling category of is Stationary with sale of 390$



In [54]:
# Identify which categories has sales below the overall monthly average across all weeks.
overall_avg=fullMonth.mean()
avg_per_category=fullMonth.mean(axis=0)
category_below_avg=np.where(avg_per_category<overall_avg,True,False)
print(category_below_avg)
# print("Categories' sales below the overall monthly average across all weeks: \n",category*category_below_avg)
print(overall_avg)
print(avg_per_category)

[False  True  True False  True]
979.75
[1157.5   897.5   343.75 1762.5   737.5 ]
