# Working with a sensor network that logs readings every hour. Reveive data in two separate shifts(morining and evening), each with 3 sensors.

In [1]:
import numpy as np 
morning = np.array([
    [22.1, 45.3, 0.91],
    [22.5, 46.1, 0.89],
    [23.0, 47.5, 0.87],
    [23.8, 48.2, 0.85],
    [24.1, 49.0, 0.84],
    [24.5, 49.8, 0.82]
])  # 6 hours × 3 sensors

evening = np.array([
    [26.3, 55.1, 0.78],
    [25.9, 54.3, 0.80],
    [25.4, 53.0, 0.81],
    [24.8, 51.7, 0.83],
    [24.2, 50.5, 0.84],
    [23.7, 49.2, 0.86]
])  # 6 hours × 3 sensors

In [ ]:
# Combine both shifts into a full 12-hours log.
fullShift=np.vstack([morning,evening])
print("Full Shift(12-hour) Sensor Readings:\n",fullShift)

Full Shift Sensor Readings:
 [[22.1  45.3   0.91]
 [22.5  46.1   0.89]
 [23.   47.5   0.87]
 [23.8  48.2   0.85]
 [24.1  49.    0.84]
 [24.5  49.8   0.82]
 [26.3  55.1   0.78]
 [25.9  54.3   0.8 ]
 [25.4  53.    0.81]
 [24.8  51.7   0.83]
 [24.2  50.5   0.84]
 [23.7  49.2   0.86]]


In [3]:
# Split the full log into 3 equal time blocks.
firstBlock,secondBlock,thirdBlock=np.vsplit(fullShift,3)
print("First time block log: \n",firstBlock)
print("Second time block log: \n",secondBlock)
print("Third time block log: \n",thirdBlock)

First time block log: 
 [[22.1  45.3   0.91]
 [22.5  46.1   0.89]
 [23.   47.5   0.87]
 [23.8  48.2   0.85]]
Second time block log: 
 [[24.1  49.    0.84]
 [24.5  49.8   0.82]
 [26.3  55.1   0.78]
 [25.9  54.3   0.8 ]]
Third time block log: 
 [[25.4  53.    0.81]
 [24.8  51.7   0.83]
 [24.2  50.5   0.84]
 [23.7  49.2   0.86]]


In [6]:
# For each block, compute the mean of each sensor.
Block1Mean=firstBlock.mean(axis=0)
Block2Mean=secondBlock.mean(axis=0)
Block3Mean=thirdBlock.mean(axis=0)

print("First Blocks' sensors mean: ",Block1Mean)
print("Second Blocks' sensors mean: ",Block2Mean)
print("Third Blocks' sensors mean: ",Block3Mean)


First Blocks' sensors mean:  [22.85  46.775  0.88 ]
Second Blocks' sensors mean:  [25.2  52.05  0.81]
Third Blocks' sensors mean:  [24.525 51.1    0.835]


In [7]:
# Stack the 3 mean rows into a summary array of shape(3,3) -> each row=one block's averages
summary_arr=np.vstack([Block1Mean,Block2Mean,Block3Mean])
print("The mean summary array : \n",summary_arr)

The mean summary array : 
 [[22.85  46.775  0.88 ]
 [25.2   52.05   0.81 ]
 [24.525 51.1    0.835]]
