# Arithmetic Operations on 2D Arrays

In [4]:
import numpy as np 
a=np.arange(1,7,1).reshape(2,3)
b=np.arange(10,61,10).reshape(2,3)

In [5]:
# Add a and b.
print(a+b)

[[11 22 33]
 [44 55 66]]


In [6]:
# Subtract a and b.
print(b-a)

[[ 9 18 27]
 [36 45 54]]


In [7]:
# Multiply a and b.
print(a*b)

[[ 10  40  90]
 [160 250 360]]


In [8]:
# Divide b by a.
print(b/a )

[[10. 10. 10.]
 [10. 10. 10.]]


In [9]:
# Find the square fo every element in a.
print(a**2)

[[ 1  4  9]
 [16 25 36]]


In [10]:
# Add 5 to every element of a.
print(a+5)

[[ 6  7  8]
 [ 9 10 11]]


In [11]:
# Multiply every element of b by 3.
print(b*3)

[[ 30  60  90]
 [120 150 180]]


In [12]:
# Computer (a+b)/2
print((a+b)/2)

[[ 5.5 11.  16.5]
 [22.  27.5 33. ]]
