# Arithmetic Operations on 1D Arrays

In [1]:
import numpy as np 
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])

In [2]:
# Add a and b.
print(a+b)

[11 22 33 44 55]


In [3]:
# Subtract b from a
print(a-b)

[ 9 18 27 36 45]


In [4]:
# Multiply a and b.
print(a*b)

[ 10  40  90 160 250]


In [5]:
# Divide a by b.
print(a/b)

[10. 10. 10. 10. 10.]


In [6]:
# find a%b.
print(a%b)

[0 0 0 0 0]


In [7]:
# Calculate a ** b
print(a**b)

[       10       400     27000   2560000 312500000]


In [8]:
# Multiply every element of a by 10.
print(a*10)

[100 200 300 400 500]


In [9]:
# Add 100 to every element of b.
print(b+100)

[101 102 103 104 105]


In [10]:
# Divide all elements of a by 2.
print(a/2)

[ 5. 10. 15. 20. 25.]


In [11]:
# Compute (a+b)/2
print((a+b)/2)

[ 5.5 11.  16.5 22.  27.5]
