Simulating a stock price walk for 5 assets over 252 trading days(1 year):

In [1]:
import numpy as np 
np.random.seed(3)
start_prices = np.array([150., 280., 95., 420., 60.])

In [2]:
# Generate daily returns as normal(loc=0.0005,scale=0.02,size=(252,5))
daily_returns=np.random.normal(loc=0.0005,scale=0.02,size=(252,5))
print("Daily returns shape: ",daily_returns.shape)

Daily returns shape:  (252, 5)


In [3]:
# Compute comulative price series.
prices=start_prices*np.cumprod(1+daily_returns,axis=0)
print(prices)

[[155.44088542 282.58445516  95.23084519 404.55666129  59.69713416]
 [154.41572487 282.25811826  94.08426452 404.40440098  59.15721175]
 [150.43530516 287.39308429  95.78966985 418.43378059  59.24598737]
 ...
 [211.72358472 497.8979717   53.25504805 442.40226145  51.87758511]
 [209.1315732  483.89766128  52.78737419 453.0464127   50.85558214]
 [212.39501558 487.80492411  53.56200697 450.19153576  50.82240861]]


In [4]:
# Find the final price of each asset after 252 days.
final_price=prices[-1]
print("Final price of each asset after 252 days:\n",final_price)

Final price of each asset after 252 days:
 [212.39501558 487.80492411  53.56200697 450.19153576  50.82240861]


In [5]:
# Find which asset had the highest single-day percentage gain across the entire simulation on the flattend returns.
max_gain_index = np.argmax(daily_returns)
day,asset=divmod(max_gain_index,daily_returns.shape[1])
max_gain_value=daily_returns[day,asset]
print(f"The highest single-day percentage gain asset was Asset{asset+1} with percentage gain of {max_gain_value*100:.2f}%")

The highest single-day percentage gain asset was Asset4 with percentage gain of 7.45%


In [6]:
# Find the worst day overall(largest single_day drop).
min_drop_index = np.argmin(daily_returns)          # flat index of worst return
day, asset = divmod(min_drop_index, daily_returns.shape[1])
min_drop_value = daily_returns[day, asset]
print(f"The worst day overall is Day{day+1} with largest single-day drop of {min_drop_value*100:.2f}%")

The worst day overall is Day213 with largest single-day drop of -6.00%
