Challenge 1

In [1]:
import numpy as np 
sales = np.array([
    [120,140,160,180],
    [100,220,130,150],
    [190,170,210,110],
    [250,90,180,200]
])

In [14]:
# Find the top five sales values.
top_indices=np.argsort(sales,axis=None)[::-1]
top_5indices=top_indices[:5]

coords=[np.unravel_index(idx,sales.shape) for idx in top_5indices]
top5_values=sales.flatten()[top_5indices]
print("Top 5 sales values: ",top5_values)

# Determine their positions.
for val,pos in zip(top5_values,coords):
    print(f"Value: {val}, Position: ({pos[0]},{pos[1]})")

Top 5 sales values:  [250 220 210 200 190]
Value: 250, Position: (3,0)
Value: 220, Position: (1,1)
Value: 210, Position: (2,2)
Value: 200, Position: (3,3)
Value: 190, Position: (2,0)


In [19]:
# Calculate the sum of all values above overall average.
overall_avg=sales.mean()
flat_sales=sales.flatten()
sum_above_avg=flat_sales[flat_sales>overall_avg].sum()
print("Sum of all values above overall average: ",sum_above_avg)

Sum of all values above overall average:  1600


In [22]:
# Find the branch contributing the highest revenue.
revenue_per_branch=sales.sum(axis=0) # columns as branch
print(f"Branch contributing the highest revenue is Branch{np.argmax(revenue_per_branch)+1} with revenue of ${revenue_per_branch[np.argmax(revenue_per_branch)]}.")

Branch contributing the highest revenue is Branch3 with revenue of $680.


In [23]:
# Find the revenue difference between best and worst branch.
print(f"Revenue diff between best and worst branch is of ${revenue_per_branch[np.argmax(revenue_per_branch)]-revenue_per_branch[np.argmin(revenue_per_branch)]}.")

Revenue diff between best and worst branch is of $60.


Challenge 2

In [33]:
np.random.seed(33)
data=np.arange(1,101)
np.random.shuffle(data)
data=data.reshape(10,10)
print("Data:\n",data)

Data:
 [[ 57  91  96  83  61  72   7  82   3  71]
 [ 97  63  60  87  42  40   5  35 100  73]
 [ 79  98  30  85  39  44  47   6  92  52]
 [ 28  18  10  70  38  77  14  65   1   9]
 [ 22  88  25  76  41  29  59  64  55  48]
 [ 66  94  86  37  16  50   2  81  56  69]
 [ 54  31  51  90  26  53  49  33  27  80]
 [  4  75  93  11  99  95  24  20  17  23]
 [ 12  13  45  32  78  34  36  46  43  15]
 [ 84  62  68  58  74  19  67  89   8  21]]


In [34]:
# Calculate digonal sum.
diag_sum=np.trace(data)
print("Main diagonal sum: ",diag_sum)

Main diagonal sum:  444


In [35]:
# Find all positions where values are divisible by both 3 and 5.

# masking
mask=(data%3==0) & (data%5==0)

# indices
rows,cols=np.where(mask)

for r,c in zip(rows,cols):
    print(f"Value: {data[r,c]} , Position: ({r},{c})")


Value: 60 , Position: (1,2)
Value: 30 , Position: (2,2)
Value: 90 , Position: (6,3)
Value: 75 , Position: (7,1)
Value: 45 , Position: (8,2)
Value: 15 , Position: (8,9)


In [39]:
# Extract those values and rank then from highest to lowest.
extracted_values=data[mask]
print("Extracted values: ",extracted_values)

rank=np.argsort(extracted_values)[::-1]
print("Ranked: ",extracted_values[rank])

Extracted values:  [60 30 90 75 45 15]
Ranked:  [90 75 60 45 30 15]


In [40]:
# Determine the median of the extracted values.
print("The median of the extracted values: ",np.median(extracted_values))

The median of the extracted values:  52.5


In [45]:
# Find the position of the largest extracted value within the original matrix.
r,c=np.where(extracted_values.max()==data)
print(f"Largest extracted value: {data[r.item(),c.item()]} , Position in original matrix: ({r.item()},{c.item()})")


Largest extracted value: 90 , Position in original matrix: (6,3)
