# Boolean Indexing on 2D Arrays

In [5]:
import numpy as np 
arr=np.arange(10,91,10).reshape(3,3)
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [6]:
# Extract all values greater than 50.
print(arr[arr>50])


[60 70 80 90]


In [7]:
# Extract all values less than 40.
print(arr[arr<40])

[10 20 30]


In [8]:
# Count values greater than 30.
print((arr>30).sum())

6


In [9]:
# Extract all multiples of 20.
print(arr[arr%20==0])

[20 40 60 80]


In [10]:
# Replace values greater than 60 with -1.
arr[arr>60]=-1
print(arr)

[[10 20 30]
 [40 50 60]
 [-1 -1 -1]]


In [11]:
# Extract all even numbers.
print(arr[arr%2==0])

[10 20 30 40 50 60]
