Advanced Slicing

In [2]:
import numpy as np 
arr=np.arange(1,26).reshape(5,5)
print("Original matrix: \n",arr)

Original matrix: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [4]:
# Without modifying the original array, extract every second row and every second column. 
matrix=arr[1::2,1::2]
print("Resulting matrix: \n",matrix)


Resulting matrix: 
 [[ 7  9]
 [17 19]]


In [5]:
# find the sum of all corner elements of the extracted matrix.
print("Sum of corner elements of the matrix: ",matrix.sum()) #since all the elements are corner element

Sum of corner elements of the matrix:  52


Argsort

In [6]:
scores=np.array([78,92,65,88,95,70])

In [8]:
# Determine the ranking of students from lowest score to highest.
indexes=np.argsort(scores)
print("Scores: \n",scores[indexes])

Scores: 
 [65 70 78 88 92 95]


In [10]:
# Which student index would appear third in the sorted order?
print(f"Student whose index would appear third in the sorted order is Student{indexes[2]+1}")

Student whose index would appear third in the sorted order is Student1


In [12]:
# Which student has the second-highest scores?
print(f"The student with second-highest score is Student{indexes[-2]+1} with score of {scores[indexes[-2]]}")

The student with second-highest score is Student2 with score of 92


Advanced Where

In [15]:
temp=np.array([22,35,18,40,28,15])
print("Original temperature readings: \n",temp)

Original temperature readings: 
 [22 35 18 40 28 15]


In [ ]:
# Create a result where temperature above 30 becomes 1 other beomes 0
result=np.where(temp>30,1,0)
print("Result: \n",result)

Result: 
 [0 1 0 1 0 0]


In [20]:
# Find number of hot days.
print("Number of hot days(above 30): ",result.sum())
# Find the percentage of hot days.
hot_day=(arr==1).sum()
percentage=hot_day/len(result)*100
print(f"Percentage of hot days : {percentage:.2f} %")


Number of hot days(above 30):  2
Percentage of hot days : 16.67 %


Nonzero

In [21]:
data=np.array([0,12,0,8,5,0,14,7])

In [28]:
# Find the position containing actaul values.
print("Position containing actual values: ",np.nonzero(data))
# What is the sum of all non-zero values?
print("Sum of non-zero values: ",data[np.nonzero(data)].sum())
# What percentage of entries are non-zero?
non_zero=data[np.nonzero(data)].size
percentage=non_zero/data.size*100
print(f"Percentage of non-zero entries: {percentage:.2f} %")

Position containing actual values:  (array([1, 3, 4, 6, 7]),)
Sum of non-zero values:  46
Percentage of non-zero entries: 62.50 %


Diag,Triu,Tril

In [29]:
A=np.arange(1,17).reshape(4,4)
print("A: \n",A)

A: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [40]:
# Find the sum of the main diagonal.
print("The sum of main diagonal: ",np.diag(A).sum())
# Find the sum of elemenets above the diagonal.
print("The sum of elements above the diagonal: ",np.triu(A,k=1).sum())
# Find the sum of elements below the diagonal.
print("The sum of elements below the diagonal: ",np.tril(A,k=-1).sum())

The sum of main diagonal:  34
The sum of elements above the diagonal:  36
The sum of elements below the diagonal:  66
