Advanced Argmax & Argmin

In [2]:
import numpy as np 
sales=np.array([
    [120,140,160],
    [180,110,170],
    [130,200,150]
])

In [6]:
# Identify the position of the highest sale.
max_coords=np.unravel_index(sales.argmax(),sales.shape)
print("Max sale: ",sales[max_coords])
print("Position(row,col): ",max_coords)

# Identify the position of the lowest sale.
min_coords=np.unravel_index(sales.argmin(),sales.shape)
print("Min sale: ",sales[min_coords])
print("Position: ",min_coords)

# Calulate the difference between them.
print("Difference: ",sales[max_coords]-sales[min_coords])

Max sale:  200
Position(row,col):  (np.int64(2), np.int64(1))
Min sale:  110
Position:  (np.int64(1), np.int64(1))
Difference:  90


In [7]:
prices=np.array([150,200,250,300,350,400,450])

In [11]:
# Extract values located at positions: 0,2,4,6
values_at=[0,2,4,6]
selected_price=prices[values_at]
print("Required values: ",selected_price)

# Determine average selected price.
print("Average of selected price: $",selected_price.mean())

# Determine Highest selected price.
print("Highest Selected price: $",selected_price.max())

# Determine difference between highest and lowest selected price.
print("Difference between highest and lowest selected price: $",selected_price.max()-selected_price.min())

Required values:  [150 250 350 450]
Average of selected price: $ 300.0
Highest Selected price: $ 450
Difference between highest and lowest selected price: $ 300


# Put


In [29]:
inventory=np.arange(10,61,10)
print("Inventory: ",inventory)

Inventory:  [10 20 30 40 50 60]


In [37]:
# Position 1,2,5 must be replaced by 100,200,300.
positions=[1,2,5]
values=[100,200,300]
new_inventory=inventory.copy()
np.put(new_inventory,positions,values)
print("New inventory: ",new_inventory)

New inventory:  [ 10 100 200  40  50 300]


In [31]:
# After replcement: 
   # 1. what is the inventory total?
print("Inventory total after replacement: $",new_inventory.sum())
   # 2. Which position contains the largest values?
print("Position with largest value: ",np.argmax(new_inventory))
   # 3. What percentage increase occurred in total inventory?
print(f"Percentage increase in total inventory: {(new_inventory.sum()-inventory.sum())/inventory.sum()*100:.2f} %")
   

Inventory total after replacement: $ 700
Position with largest value:  5
Percentage increase in total inventory: 233.33 %


# Clip


In [33]:
marks=np.array([25,45,65,85,105])

In [36]:
# Marks below to becomes 40 & marks above 100 becomes 100.
clipped_marks=np.clip(marks,40,100)
print("Clipped marks: ",clipped_marks)

# New average
print("New Average: ",clipped_marks.mean())

# Total marks removed/added due to clipping.
print("Total marks added/removed due to clipping: ",abs(marks-clipped_marks).sum())

Clipped marks:  [ 40  45  65  85 100]
New Average:  67.0
Total marks added/removed due to clipping:  20


In [3]:
data=np.arange(1,37).reshape(6,6)
print("Original data: \n",data)

Original data: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [4]:
# Extract only rows having odd indices.
row_odd_idx=data[1::2,:]
print("Rows having odd indices: \n",row_odd_idx)

Rows having odd indices: 
 [[ 7  8  9 10 11 12]
 [19 20 21 22 23 24]
 [31 32 33 34 35 36]]


In [6]:
# From the extracted result, keep only columns having even indices.
even_cols=row_odd_idx[:,::2]
print("Columns having even indices: \n",even_cols)

Columns having even indices: 
 [[ 7  9 11]
 [19 21 23]
 [31 33 35]]


In [7]:
# Find the largest value in the final matrix.
print("Largest value in the final matrix: ",even_cols.max())

Largest value in the final matrix:  35


In [14]:
# Determine its position within the extracted matrix.
coords=np.unravel_index(even_cols.argmax(),even_cols.shape)
print(f"Position of largest value in resulting matrix: ({coords[0]},{coords[1]})")

Position of largest value in resulting matrix: (2,2)


In [15]:
profits=np.array([
    420,380,510,470,
    390,600,450,530
])

In [19]:
# Rank companies from highest profit to lowest.
rank_idx=np.argsort(profits)[::-1]
ranked_profits=profits[rank_idx]
print("Ranked Companies: \n",ranked_profits)

Ranked Companies: 
 [600 530 510 470 450 420 390 380]


In [21]:
# Determine the top three companies.
top_three_comp=rank_idx[:3]
print("Top three companies are: ",top_three_comp+1)

Top three companies are:  [6 8 3]


In [22]:
# Find the difference between profits of the best and third-best company.
profit=profits[rank_idx[0]]-profits[rank_idx[2]]
print("Difference between profits of the best and third-best company: ",profit)

Difference between profits of the best and third-best company:  90


In [24]:
matrix=np.arange(1,26).reshape(5,5)
print("Matrix: \n",matrix)

Matrix: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
# Calculate diagonal sum.
diagonal_sum=np.trace(matrix)
print("The diagonal sum: ",diagonal_sum)

The diagonal sum:  65


In [33]:
# Calulate upper-triangular sum.
upp_tri_sum=np.triu(matrix,k=1).sum()
print("Upper-triangular sum: ",upp_tri_sum)

Upper-triangular sum:  90


In [34]:
# Calculate lower-triangle sum.
lwr_tri_sum=np.tril(matrix,k=-1).sum()
print("Lower triangle sum: ",lwr_tri_sum)

Lower triangle sum:  170


In [35]:
# Verify: upper+lower - diagonal= total matrix sum.
total_sum=matrix.sum()
LHS=upp_tri_sum+lwr_tri_sum+diagonal_sum
print("Is Upper+Lower-Diagonal equal to Total matrix sum?: ",np.allclose(LHS,total_sum))

Is Upper+Lower-Diagonal equal to Total matrix sum?:  True


In [36]:
sensor=np.array([
    [12,75,130],
    [55,95,210],
    [40,180,300]
])

In [37]:
# Find corrected matrix(clip min=50,max=200)
clipped_data=np.clip(sensor,50,200)
print("Corrected matrix: \n",clipped_data)

Corrected matrix: 
 [[ 50  75 130]
 [ 55  95 200]
 [ 50 180 200]]


In [ ]:
# Find new maximum.
new_max=clipped_data.max()
print("New maximum: ",new_max)

New maximum:  200


In [39]:
# Find the total reduction caused by clipping.
print("Total reduction caused by clipping: ",sensor.sum()-clipped_data.sum())

Total reduction caused by clipping:  62
