# Fancy Indexing

In [ ]:
import numpy as np 
arr=np.arange(100,801,100)
print(arr)

[100 200 300 400 500 600 700 800]


In [2]:
# Exract[100,300,500].
print(arr[[0,2,4]])

[100 300 500]


In [3]:
# Extract [800,600,400].
print(arr[[7,5,3]])

[800 600 400]


In [ ]:
# Extract first,middle,and last elements.
print(arr[[0,(len(arr)//2),-1]])  # // integer division operator

[100 500 800]


In [8]:
# Create a new array containing elements at indices[1,3,5,7]
new_arr=arr[[1,3,5,7]]
print(new_arr)

[200 400 600 800]


In [9]:
# Repeat the first element three times using fancy indexing.
print(arr[[0,0,0]])

[100 100 100]
