Simulate a biased coin - heads appears 70% of the time, tails 30%.

In [9]:
import numpy as np 
flips=np.random.choice(["H","T"],size=1000,p=[0.7,0.3])

# Count heads and tails using Boolean conditions
heads=np.sum(flips=="H")
tails=np.sum(flips=="T")

# Report results
print("Heads: ",heads)
print("Tails: ",tails)

# Check closeness to expected ratio
ratio_heads = heads / 1000
ratio_tails = tails / 1000
print("Heads ratio:", ratio_heads)
print("Tails ratio:", ratio_tails)

if abs(ratio_heads - 0.7) < 0.05 and abs(ratio_tails - 0.3) < 0.05:
    print("✅ The actual ratio is close to the expected 70/30 split.")
else:
    print("⚠️ The ratio deviates noticeably from 70/30.")

Heads:  687
Tails:  313
Heads ratio: 0.687
Tails ratio: 0.313
✅ The actual ratio is close to the expected 70/30 split.


A dataset of 50 students scores:

In [ ]:
np.random.seed(21)
scores = np.random.normal(loc=72, scale=12, size=50).clip(0, 100).astype(int)
# About two-third random values will be close to 72(with magnitude above or below by 12)
print(scores)

[71 70 84 56 80 51 69 69 85 71 64 88 91 63 80 66 73 75 56 72 59 60 66 48
 54 74 79 82 66 80 90 86 55 51 76 86 71 83 74 74 75 74 66 94 83 65 68 59
 77 54]


In [15]:
# Shuffle the scores and pick the first 10 as a "random sample".
np.random.shuffle(scores)
rand_samples=scores[:11]
print("First 10 random samples: ",rand_samples)

First 10 random samples:  [83 65 86 75 94 71 79 72 59 88 71]


In [16]:
# From that sample, find the min, max & mean.
print("Minimum value: ",rand_samples.min())
print("Maximum value: ",rand_samples.max())
print("Mean value: ",rand_samples.mean())

Minimum value:  59
Maximum value:  94
Mean value:  76.63636363636364


In [19]:
# Repeat the process using choice() with replace=False instead of shuffle.
rand_samples=np.random.choice(scores,size=10,replace=False)
print("Random Samples: ",rand_samples)
print("Minimum value: ",rand_samples.min())
print("Maximum value: ",rand_samples.max())
print("Mean value: ",rand_samples.mean())

Random Samples:  [64 77 83 72 76 80 74 74 63 56]
Minimum value:  56
Maximum value:  83
Mean value:  71.9


Generate a 6x6 grid of random integers between 1 and 100.

In [24]:
data=np.random.randint(1,101,size=(6,6))
print("Generated 6x6 random integers grid: \n",data)


Generated 6x6 random integers grid: 
 [[ 3 16 52 44 82 42]
 [46 75 16 74  3 37]
 [41  4 25 16 25 92]
 [49 86 22 59 51 10]
 [ 6 23 30 94 77 11]
 [67  5 99 26  7 61]]


In [25]:
# Replace all values above 80 with the value 99
data=np.where(data<20,1,data)
data=np.where(data>80,99,data)
print("Clipped data: \n",data)

Clipped data: 
 [[ 1  1 52 44 99 42]
 [46 75  1 74  1 37]
 [41  1 25  1 25 99]
 [49 99 22 59 51  1]
 [ 1 23 30 99 77  1]
 [67  1 99 26  1 61]]


In [26]:
# Report how many cells are above 80 and how many are below 20.
above_80=np.sum(data>80)
below_20=np.sum(data<20)
print("Cells count above 80: ",above_80)
print("Cells count below 20: ",below_20)

Cells count above 80:  5
Cells count below 20:  11


Simulate rolling two 6-sided dice 10,000 times and build a frequency table of the sums.

In [27]:
np.random.seed(0)

In [28]:
# Generate both dice rolls in one step as a (10000,2) array.
dice_rolls=np.random.randint(1,7,size=(10000,2))
print("Results: \n",dice_rolls)

Results: 
 [[5 6]
 [1 4]
 [4 4]
 ...
 [4 6]
 [5 6]
 [4 2]]


In [29]:
# Sum along axis=1 to get total scores(range 2-12).
sums=dice_rolls.sum(axis=1)
print("Sums: ",sums)

Sums:  [11  5  8 ... 10 11  6]


In [ ]:
# Build freqeuncy table.
unique_sums,counts=np.unique(sums,return_counts=True)
