Simulate a biased coin - heads appears 70% of the time, tails 30%.

In [9]:
import numpy as np 
flips=np.random.choice(["H","T"],size=1000,p=[0.7,0.3])

# Count heads and tails using Boolean conditions
heads=np.sum(flips=="H")
tails=np.sum(flips=="T")

# Report results
print("Heads: ",heads)
print("Tails: ",tails)

# Check closeness to expected ratio
ratio_heads = heads / 1000
ratio_tails = tails / 1000
print("Heads ratio:", ratio_heads)
print("Tails ratio:", ratio_tails)

if abs(ratio_heads - 0.7) < 0.05 and abs(ratio_tails - 0.3) < 0.05:
    print("✅ The actual ratio is close to the expected 70/30 split.")
else:
    print("⚠️ The ratio deviates noticeably from 70/30.")

Heads:  687
Tails:  313
Heads ratio: 0.687
Tails ratio: 0.313
✅ The actual ratio is close to the expected 70/30 split.


A dataset of 50 students scores:

In [ ]:
np.random.seed(21)
scores = np.random.normal(loc=72, scale=12, size=50).clip(0, 100).astype(int)
# About two-third random values will be close to 72(with magnitude above or below by 12)
print(scores)

[71 70 84 56 80 51 69 69 85 71 64 88 91 63 80 66 73 75 56 72 59 60 66 48
 54 74 79 82 66 80 90 86 55 51 76 86 71 83 74 74 75 74 66 94 83 65 68 59
 77 54]


In [15]:
# Shuffle the scores and pick the first 10 as a "random sample".
np.random.shuffle(scores)
rand_samples=scores[:11]
print("First 10 random samples: ",rand_samples)

First 10 random samples:  [83 65 86 75 94 71 79 72 59 88 71]


In [16]:
# From that sample, find the min, max & mean.
print("Minimum value: ",rand_samples.min())
print("Maximum value: ",rand_samples.max())
print("Mean value: ",rand_samples.mean())

Minimum value:  59
Maximum value:  94
Mean value:  76.63636363636364


In [19]:
# Repeat the process using choice() with replace=False instead of shuffle.
rand_samples=np.random.choice(scores,size=10,replace=False)
print("Random Samples: ",rand_samples)
print("Minimum value: ",rand_samples.min())
print("Maximum value: ",rand_samples.max())
print("Mean value: ",rand_samples.mean())

Random Samples:  [64 77 83 72 76 80 74 74 63 56]
Minimum value:  56
Maximum value:  83
Mean value:  71.9


Generate a 6x6 grid of random integers between 1 and 100.

In [24]:
data=np.random.randint(1,101,size=(6,6))
print("Generated 6x6 random integers grid: \n",data)


Generated 6x6 random integers grid: 
 [[ 3 16 52 44 82 42]
 [46 75 16 74  3 37]
 [41  4 25 16 25 92]
 [49 86 22 59 51 10]
 [ 6 23 30 94 77 11]
 [67  5 99 26  7 61]]


In [25]:
# Replace all values above 80 with the value 99
data=np.where(data<20,1,data)
data=np.where(data>80,99,data)
print("Clipped data: \n",data)

Clipped data: 
 [[ 1  1 52 44 99 42]
 [46 75  1 74  1 37]
 [41  1 25  1 25 99]
 [49 99 22 59 51  1]
 [ 1 23 30 99 77  1]
 [67  1 99 26  1 61]]


In [26]:
# Report how many cells are above 80 and how many are below 20.
above_80=np.sum(data>80)
below_20=np.sum(data<20)
print("Cells count above 80: ",above_80)
print("Cells count below 20: ",below_20)

Cells count above 80:  5
Cells count below 20:  11


Simulate rolling two 6-sided dice 10,000 times and build a frequency table of the sums.

In [27]:
np.random.seed(0)

In [28]:
# Generate both dice rolls in one step as a (10000,2) array.
dice_rolls=np.random.randint(1,7,size=(10000,2))
print("Results: \n",dice_rolls)

Results: 
 [[5 6]
 [1 4]
 [4 4]
 ...
 [4 6]
 [5 6]
 [4 2]]


In [29]:
# Sum along axis=1 to get total scores(range 2-12).
sums=dice_rolls.sum(axis=1)
print("Sums: ",sums)

Sums:  [11  5  8 ... 10 11  6]


In [30]:
# Build freqeuncy table.
unique_sums,counts=np.unique(sums,return_counts=True)
freq_table=np.column_stack([unique_sums,counts])
print("Frequency Table: \n",freq_table)


Frequency Table: 
 [[   2  281]
 [   3  550]
 [   4  856]
 [   5 1080]
 [   6 1364]
 [   7 1706]
 [   8 1398]
 [   9 1094]
 [  10  830]
 [  11  536]
 [  12  305]]


In [32]:
# Find most frequent sum.
most_frequent_idx=np.argmax(counts)
most_frequent_sum=unique_sums[most_frequent_idx]
print("The most frequent sum: ",most_frequent_sum)

The most frequent sum:  7


A sales dataset for 5 products over 30 days.

In [33]:
np.random.seed(7)
sales = np.random.randint(50, 500, size=(30, 5))
# rows = days, cols = products

In [36]:
# Spilt into 3 equal block of days.
block1,block2,block3=np.vsplit(sales,3)
print("First 10 day block: \n",block1)
print("Second 10 day block: \n",block2)
print("Third 10 day block: \n",block3)

First 10 day block: 
 [[225 246  75 117 261]
 [457 153 398 235 448]
 [ 73 122 395 416  92]
 [268 442 217 118 482]
 [433 441 478  50 125]
 [361 300  56 325 494]
 [ 94 241 375 362 202]
 [233 487 162 301 239]
 [498 340 362 251  88]
 [310 187 393 245 122]]
Second 10 day block: 
 [[389 482 307 242 450]
 [424 465 399 478 142]
 [302 121 329  60 283]
 [341 498 367 441 201]
 [142 297 274 199 406]
 [469 117 429 269  69]
 [461  54 325  83 173]
 [336 235 279 379 433]
 [465 180 133 484 452]
 [ 71 169 117 253 492]]
Third 10 day block: 
 [[ 97 322  62 399 157]
 [283 443 382 373 160]
 [192 174 326 359 449]
 [365  85 354 310 349]
 [300 104  93 265 484]
 [ 89 181 463 446 385]
 [335 186 104 216 423]
 [248 199  94 185 259]
 [247 150 230 219  79]
 [332 370 302 240 264]]


In [38]:
# For each block, compute total sales per product.
Tsales_block1=np.sum(block1,axis=0)
print("Total sales per product in Block1: ",Tsales_block1)
Tsales_block2=np.sum(block2,axis=0)
print("Total sales per product in Block2: ",Tsales_block2)
Tsales_block3=np.sum(block3,axis=0)
print("Total sales per product in Block3: ",Tsales_block3)

Total sales per product in Block1:  [2952 2959 2911 2420 2553]
Total sales per product in Block2:  [3400 2618 2959 2888 3101]
Total sales per product in Block3:  [2488 2214 2410 3012 3009]


In [43]:
# Stack the 3 totals into a (3,5) summary.
summary=np.column_stack([Tsales_block1,Tsales_block2,Tsales_block3])
print("Summary: \n",summary)

Summary: 
 [[2952 3400 2488]
 [2959 2618 2214]
 [2911 2959 2410]
 [2420 2888 3012]
 [2553 3101 3009]]


In [44]:
# Shuffle the rows of the summary to simulate randomized reporting order.
np.random.shuffle(summary)
print("Shuffled summary: \n",summary)

Shuffled summary: 
 [[2959 2618 2214]
 [2420 2888 3012]
 [2553 3101 3009]
 [2952 3400 2488]
 [2911 2959 2410]]


In [53]:
# Identify which product had the highest total across all 30 days using argmax.
highestT_sales=np.sum(sales,axis=0)
highestS_prod_idx=np.argmax(highestT_sales)
print(f"The product that had the highest total sales across all 30 days was Product{highestS_prod_idx+1} with sales of ${highestT_sales[highestS_prod_idx]}.")

The product that had the highest total sales across all 30 days was Product1 with sales of $8840.


Generate a dataset of 200 samples from a normal distribution(mean=50,std=10) and 200 samples from a uniform distribution(range 30-70).