# Reshape, Transpose, Flatten and Ravel

Shape

In [1]:
import numpy as np 
arr=np.arange(24)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [2]:
# Reshape into 2D
print("Reshaped Arrar: \n",arr.reshape(6,4))

Reshaped Arrar: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
# Reshape into 3D array
print("Reshaped into 3D: \n",arr.reshape(4,3,2))

Reshaped into 3D: 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [6]:
# Reshape into another 2D shape
print("Reshaped in 2D again: \n",arr.reshape(2,12))

Reshaped in 2D again: 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [10]:
# Flatten a 2D array
arr=np.arange(20).reshape(5,4)
print("Original Array: \n",arr)
print("Flatten Array: \n",arr.flatten())
print("Array: \n",arr) # Flatten just makes copy of array and return(original unaffected)

Original Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Flatten Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
# Ravel the array
print("Array Ravel: \n",arr.ravel())


Array Before Ravel: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Array Ravel: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array After Ravel: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


# Visualizing Reshape