# zeros(), ones(), & empty()

In [1]:
# Create a 1D arry of 10 zeros.
import numpy as np 
zeros_array=np.zeros(10)
print(zeros_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Create a 3 x 4 array of ones.
ones_array=np.ones((3,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# Create a 2 x 3 x 4 array filled with zeros.
ar=np.zeros((2,3,4))
print(ar)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [9]:
# Create a 5 x 5 array of ones with data type float32.
arr=np.ones((5,5),dtype=np.float32)
print(arr)
print(arr.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float32


In [ ]:
# Create a 4 x4 array using emtpy().(Stores garbage values need to override)
arr=np.empty((4,4))
print(arr)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 2.12199579e-314]]


In [11]:
# Create a 6 x 3 array of ones and caculate its sum.
arr=np.ones((6,3))
print(arr.sum())

18.0
