# Challenge Questions

In [1]:
import numpy as np 

In [5]:
# Create two random arrays of shape(5,5) and perform all arithemtic operations.
arr1=np.random.randint(1,50,25).reshape(5,5)
print(arr1)


[[31 38 20 45  6]
 [21 16  7 48 48]
 [21 15 35  5 36]
 [49 33 32  3 13]
 [45  1 17 19  1]]


In [6]:
arr2=np.random.randint(1,50,25).reshape(5,5)
print(arr2)

[[15  5 23  4 31]
 [48 16 48 16 39]
 [32 15 27 46 11]
 [19  8 22 14  3]
 [14  7 13 32 33]]


In [7]:
print("Sum: \n",arr1+arr2)
print("Difference: \n",arr1-arr2)
print("Product: \n",arr1*arr2)
print("Division: \n",arr1-arr2)
print("Modulo: \n",arr1%arr2)

Sum: 
 [[46 43 43 49 37]
 [69 32 55 64 87]
 [53 30 62 51 47]
 [68 41 54 17 16]
 [59  8 30 51 34]]
Difference: 
 [[ 16  33  -3  41 -25]
 [-27   0 -41  32   9]
 [-11   0   8 -41  25]
 [ 30  25  10 -11  10]
 [ 31  -6   4 -13 -32]]
Product: 
 [[ 465  190  460  180  186]
 [1008  256  336  768 1872]
 [ 672  225  945  230  396]
 [ 931  264  704   42   39]
 [ 630    7  221  608   33]]
Division: 
 [[ 16  33  -3  41 -25]
 [-27   0 -41  32   9]
 [-11   0   8 -41  25]
 [ 30  25  10 -11  10]
 [ 31  -6   4 -13 -32]]
Modulo: 
 [[ 1  3 20  1  6]
 [21  0  7  0  9]
 [21  0  8  5  3]
 [11  1 10  3  1]
 [ 3  1  4 19  1]]


In [8]:
print("Sum of total elements of arr1: ",arr1.sum())
print("Sum of total elements of arr2: ",arr2.sum())

Sum of total elements of arr1:  605
Sum of total elements of arr2:  541


In [9]:
# Create a matrix and add row-wise bonuses using broadcasting.
matrix=np.arange(1,10,1).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
row_wise=np.array([[10],[20],[30]])
print("Row wise addition :\n",row_wise+matrix)

Row wise addition :
 [[11 12 13]
 [24 25 26]
 [37 38 39]]


In [13]:
# Create a matrix and add column-wise bonuses using broadcasting.
coln_wise=np.array([10,20,30])
print("Column wise addition: \n",matrix+coln_wise)

Column wise addition: 
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [15]:
# Normalize an array by dividing each element by the maximum value.
print("Normalized array: \n",np.round(matrix/matrix.max(),2))

Normalized array: 
 [[0.11 0.22 0.33]
 [0.44 0.56 0.67]
 [0.78 0.89 1.  ]]


In [16]:
# Compute the percentage increase between two arrays element-wise.
array1=np.arange(1,10,1).reshape(3,3)
array2=np.arange(10,19,1).reshape(3,3)
print("Array 1: \n",array1)
print("Array 2: \n",array2)

Array 1: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2: 
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [19]:
array3=((array2-array1)/array2)*100
print("Element-wise % increase\n",array3)

Element-wise % increase
 [[90.         81.81818182 75.        ]
 [69.23076923 64.28571429 60.        ]
 [56.25       52.94117647 50.        ]]


In [20]:
# Create a 4x4 matrix and multiply each row by a different value using broadcasting.
matrix4=np.arange(1,17,1).reshape(4,4)
print(matrix4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
row_multiplier=np.array([[2],[4],[6],[8]])
print("Row-wise multiplication 2R1,4R2,6R3,8R4:\n",matrix4*row_multiplier)

Row-wise multiplication 2R1,4R2,6R3,8R4:
 [[  2   4   6   8]
 [ 20  24  28  32]
 [ 54  60  66  72]
 [104 112 120 128]]


In [23]:
# Without loops, calculated the square and cube for all elements in a random array.
random_arr=np.random.randint(1,9,16).reshape(4,4)
print("Random array: \n",random_arr)

Random array: 
 [[5 8 4 1]
 [8 2 6 7]
 [6 1 8 5]
 [5 4 4 7]]


In [24]:
print("Squared random array: \n",np.square(random_arr))

Squared random array: 
 [[25 64 16  1]
 [64  4 36 49]
 [36  1 64 25]
 [25 16 16 49]]


In [25]:
print("Cube element of random array:\n",np.power(random_arr,3))

Cube element of random array:
 [[125 512  64   1]
 [512   8 216 343]
 [216   1 512 125]
 [125  64  64 343]]
