# Given an array of temperatures. Without using any loop or if, replace: 
  * Values above 35 -> "Hot"
  * Values equal and below -> "Normal"

In [3]:
import numpy as np 
arr=np.array([45,34,24,54,23,19,43,31,37,26])
print("Result: ",np.where(arr>35,"Hot","Normal"))

Result:  ['Hot' 'Normal' 'Normal' 'Hot' 'Normal' 'Normal' 'Hot' 'Normal' 'Hot'
 'Normal']


# Given two arrays a and b of same shape, build a result array that picks from a where a > b, else picks from b.

In [4]:
a=np.random.randint(1,10,9).reshape(3,3)
print(a)

[[4 7 2]
 [8 1 1]
 [4 3 8]]


In [5]:
b=np.random.randint(1,10,9).reshape(3,3)
print(b)

[[2 2 5]
 [7 2 1]
 [1 7 8]]


In [6]:
result=np.where(a>b,a,b)
print(result)

[[4 7 5]
 [8 2 1]
 [4 7 8]]


# You have an array of integers. Replace all even numbers with 0 and all odd numbers with 1 using np.where().

In [7]:
arr=np.random.randint(-10,10,16).reshape(4,4)
print(arr)

[[  4  -1  -7  -5]
 [  7   9 -10   5]
 [ -2  -7  -1  -8]
 [  9   3   8   0]]


In [8]:
result=np.where(arr%2==0,0,1)
print(result)

[[0 1 1 1]
 [1 1 0 1]
 [0 1 1 0]
 [1 1 0 0]]


# Simulate a grading system: marks array -> return "Pass" if >= 40, else "Fail". Then count how many passed without using a loop.

In [13]:
marks=np.random.randint(25,100,20)
print(marks)

[28 78 45 99 55 31 29 60 86 45 76 37 70 78 66 82 90 83 35 69]


In [17]:
result=np.where(marks>=40,"Pass","Fail")
print(result)

['Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass' 'Pass' 'Pass'
 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass']


In [18]:
print("Number of passed students: ",np.sum(result=="Pass"))

Number of passed students:  15


# Use nested np.where() to assign greader: A(>=80), B(>=60), C(>=40),F(<40)

In [22]:
marks=np.random.randint(15,100,30)
print(marks)

[60 41 51 21 69 27 21 83 80 99 92 38 75 60 65 58 90 90 54 97 46 35 63 45
 50 91 58 57 60 81]


In [23]:
grades=np.where(marks>=80,'A',np.where(marks>=60,'B',np.where(marks>=40,'C','F')))
print(grades)

['B' 'C' 'C' 'F' 'B' 'F' 'F' 'A' 'A' 'A' 'A' 'F' 'B' 'B' 'B' 'C' 'A' 'A'
 'C' 'A' 'C' 'F' 'B' 'C' 'C' 'A' 'C' 'C' 'B' 'A']
