# Boolean Indexing

In [2]:
import numpy as np
arr=np.array([12,5,18,7,25,30,9,14])

In [3]:
# Extract elements greater than 15.
print(arr[arr>15])

[18 25 30]


In [4]:
# Extract elements less than 10.
print(arr[arr<10])

[5 7 9]


In [6]:
# Extract odd numbers.
print(arr[arr%2!=0])

[ 5  7 25  9]


In [7]:
# Extract even numbers.
print(arr[arr%2==0])

[12 18 30 14]


In [12]:
# Extract elements between 10 and 25
print(arr[(arr>10) & (arr<25)])

[12 18 14]


In [ ]:
# Count how many elements are greater than 15.
print((arr>15).sum())

7
