# Slicing 2D Arrays

In [1]:
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [3]:
# Extract the first row.
print(arr[0,:])

[1 2 3 4 5]


In [4]:
# Extract the last row.
print(arr[-1,:])

[21 22 23 24 25]


In [5]:
# Extract the first column.
print(arr[:,0])

[ 1  6 11 16 21]


In [6]:
# Extract the last column.
print(arr[:,-1])

[ 5 10 15 20 25]


In [10]:
# Extract the top-left 3x3 submatrix.
submatrix=arr[:3,:3]
print(submatrix)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [11]:
# Extract the bottom-right 2x2 submatrix
print(arr[-2:,-2:])

[[19 20]
 [24 25]]


In [15]:
# Extract the rows 1-3 and columns 2-4.
print("Rows: \n",arr[:3,1:4])

Rows: 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [16]:
# Extract all even-numbered rows.
print(arr[::2,:])

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [17]:
# Extract all odd-numbered colunns.
print(arr[:,1::2])

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]


In [18]:
# Reverse both rows and columns
print(arr[::-1,::-1])

[[25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
