# Two vectors representing a user's feature profile and item weights in a recommendation system:

In [1]:
import numpy as np 
user   = np.array([0.8, 0.3, 0.9, 0.5, 0.7])
item   = np.array([0.6, 0.9, 0.4, 0.8, 0.2])

In [16]:
# Compute the dot product.
raw_dot=np.dot(user,item)
print("The Dot product of user and item is: ",np.round(raw_dot,2))

The Dot product of user and item is:  1.65


In [11]:
# Normalize both vectors(divide each by its own magnitude using np.linalg.norm())
user_norm=user/np.linalg.norm(user)
item_norm=item/np.linalg.norm(user)
print("Normalized user vector: ",user_norm)
print("Normalized item vector: ",item_norm)

Normalized user vector:  [0.52981294 0.19867985 0.59603956 0.33113309 0.46358632]
Normalized item vector:  [0.39735971 0.59603956 0.26490647 0.52981294 0.13245324]


In [18]:
# Dot product of normalized vectors
cosine_sim=np.dot(user_norm,item_norm)
print("Cosine similarity: ",cosine_sim)

Cosine similarity:  0.7707588001729145


What does the second result represents and why is it bounded between -1 and 1?
 * The second result represents normalized dot product which is called cosine similirity.
 * It is bounded between -1 and 1 because it is mathematically defined as the cosine of the angle between two vectors. 

# A transformation matrix and a batch of 4 data points(each row is a point)

In [19]:
T = np.array([[2, 0],
              [0, 3]])

points = np.array([[1, 1],
                   [2, 1],
                   [1, 3],
                   [2, 2]])

In [21]:
# Apply the transformation to all points in one operation.
result=points @ T
print("Original points: \n",points)
print("The Transformed points: \n",result)
print("\n Result shape: ",result.shape)

Original points: 
 [[1 1]
 [2 1]
 [1 3]
 [2 2]]
The Transformed points: 
 [[2 3]
 [4 3]
 [2 9]
 [4 6]]

 Result shape:  (4, 2)


# Three matrics:

In [22]:
A = np.array([[4, 7], [2, 6]])
B = np.array([[1, 0], [0, 1]])
C = np.array([[2, 4], [1, 2]])

In [24]:
# Compute determinant for each.
detA=np.linalg.det(A)
detB=np.linalg.det(B)
detC=np.linalg.det(C)
print("Determinant of A: ",np.round(detA,2))
print("Determinant of B: ",detB)
print("Determinant of C: ",detC)

Determinant of A:  10.0
Determinant of B:  1.0
Determinant of C:  0.0


Matrix C is invertible because it is a singular matrix(i.e. det=0)

In [25]:
# Invert possible matrices
invA=np.linalg.inv(A)
invB=np.linalg.inv(B)
print("Inverse of A : \n",invA)
print("Inverse of B : \n",invB)

Inverse of A : 
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Inverse of B : 
 [[1. 0.]
 [0. 1.]]
