# Ravel(modifies original array)

In [1]:
import numpy as np 
arr=np.arange(1,13).reshape(3,4)
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [2]:
# Ravel the array and find the median position element.
raveled=arr.ravel()
print("Raveled Array: ",raveled) # already sorted
n=len(raveled)
if n%2==0:
    median_position=[n//2,n//2+1]
else: 
    median_position=[n//2]
print("Median Position is :",median_position)

Raveled Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Median Position is : [6, 7]


In [6]:
# Extract every third element
ele=raveled[2::3]
print("Every third elements in the raveled array : ",ele)

Every third elements in the raveled array :  [ 3  6  9 12]


In [7]:
# Find the sum of elements at odd positions.
print("Sum of elements at odd position: ",raveled[1::2].sum())

Sum of elements at odd position:  42


In [8]:
arr=np.arange(1,26).reshape(5,5)
raveled_arr=arr.ravel()
print("Original array: \n",arr)
print("Raveled Array: \n",raveled_arr)

Original array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Raveled Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [ ]:
# Calculate the sum of prime numbers.
def is_prime(n):
    if n<2:
        return False
    elif n==2:
        return True
    elif n%2==0:
        return False
    else:
        for i in range(3,int(n**0.5)+1,2):
            if n%i==0:
                return False
            return True
# Vectorization wraps a function so that it can operate elementwise operation with input of array
vec_is_prime=np.vectorize(is_prime)

prime_mask=vec_is_prime(raveled_arr)
prime_sum=raveled_arr[prime_mask].sum()
print("Prime elements are: ",raveled_arr[prime_mask])
print("Prime elemetns sum: ",prime_sum)

Prime elements are:  [ 2 11 13 17 19 23 25]
Prime elemetns sum:  110


In [13]:
# Find the average of elements greater than 10.
masked_elements=raveled_arr[raveled_arr>10]
average=masked_elements.mean()
print("Elements greater than 10: ",masked_elements)
print("Average: ",average)

Elements greater than 10:  [11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
Average:  18.0


In [14]:
# Extract all multiples of 4 and find their sum.
masked_elements=raveled_arr[raveled_arr%4==0]
result=masked_elements.sum()
print(("Masked Elements: ",masked_elements))
print("Sum of elements that are multiples of 4: ",result)

('Masked Elements: ', array([ 4,  8, 12, 16, 20, 24]))
Sum of elements that are multiples of 4:  84


In [15]:
scores=np.arange(50,86).reshape(6,6)
print("Scores: \n",scores)

Scores: 
 [[50 51 52 53 54 55]
 [56 57 58 59 60 61]
 [62 63 64 65 66 67]
 [68 69 70 71 72 73]
 [74 75 76 77 78 79]
 [80 81 82 83 84 85]]


In [16]:
flat=scores.ravel()
print("Raveled Array: \n",flat)

Raveled Array: 
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85]


In [17]:
# Find the highes 5 scores.
print("Highest 5 scores: ",flat[-5:])

Highest 5 scores:  [81 82 83 84 85]


In [20]:
# Find the percentage of scores above 70.
n=70
ele_above_n=flat[flat>n]
count_above_n=ele_above_n.size
percentage=(count_above_n/len(flat))*100
print(f"Percentage of scores above {n} is {np.round(percentage,2)}%")

Percentage of scores above 70 is 41.67%
