# Ravel(modifies original array)

In [1]:
import numpy as np 
arr=np.arange(1,13).reshape(3,4)
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
# Ravel the array and find the median position element.
raveled=arr.ravel()
print("Raveled Array: ",raveled) # already sorted
n=len(raveled)
if n%2==0:
    median_position=[n//2,n//2+1]
else: 
    median_position=[n//2]
print("Median Position is :",median_position)



Raveled Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Median Position is : [6, 7]
