# Element-wise Operations

In [6]:
import numpy as np 
arr=np.array([2,4,6,8,10])


In [7]:
# Square every element.
print(np.square(arr))

[  4  16  36  64 100]


In [8]:
# Cube every element.
print(np.power(arr,3))

[   8   64  216  512 1000]


In [10]:
# Find the reciprocal of each element.
print(np.reciprocal(arr.astype(float)))

[0.5        0.25       0.16666667 0.125      0.1       ]


In [12]:
# Add 1 to every element
print(arr+1)

[ 3  5  7  9 11]


In [13]:
# Multiply each element by itself.
print(arr*arr)

[  4  16  36  64 100]


In [14]:
# Calculate arr + arr
print(arr+arr)

[ 4  8 12 16 20]


In [15]:
# Create a new array where each element is mulitplied by 100.
new_arr=arr*100
print(new_arr)

[ 200  400  600  800 1000]
