# Mixed Practice

In [ ]:
# Create a 5 x 5 identity matix and add it to a 5 x 5 matix of ones.
import numpy as np 
identitymat=np.identity(5)
onesmat=np.ones((5,5))
print("Identity Matrix: \n",identitymat)
print("Ones matrix: \n",onesmat)
print("Sum: \n",identitymat+onesmat)

Identity Matrix: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Ones matrix: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Sum: 
 [[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [4]:
# Create two random 3 x 3 matrices and add them.
randmat1=np.random.randint(0,10,size=(3,3))
randmat2=np.random.randint(0,10,size=(3,3))
print("Matrix 1 : \n",randmat1)
print("Matrix 2 : \n",randmat2)
print("Sum : \n",randmat1+randmat2)


Matrix 1 : 
 [[5 0 4]
 [2 9 0]
 [6 7 7]]
Matrix 2 : 
 [[8 2 7]
 [3 9 4]
 [4 5 3]]
Sum : 
 [[13  2 11]
 [ 5 18  4]
 [10 12 10]]


In [10]:
# Generate a linspace() array from 0 to 100 and reshape it into a 5 x 2 matrix.
arr=np.linspace(1,100,10)
matrix=arr.reshape(5,2)
print("linspace array: \n",arr)
print("Reshped matrix : \n",matrix)


linspace array: 
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
Reshped matrix : 
 [[  1.  12.]
 [ 23.  34.]
 [ 45.  56.]
 [ 67.  78.]
 [ 89. 100.]]


In [14]:
# Create a 4 x 4 zero matrix and replace its dialognal element with 1.
zero=np.zeros((4,4),dtype=int)
np.fill_diagonal(zero,1)
print(zero)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [18]:
# Generate a random 5 x 5 matrix and calculate the sum of each row.
randmat=np.random.randint(0,10,size=(5,5))
row_sum=np.sum(randmat,axis=1)
print(randmat)
print(row_sum)

[[6 6 1 0 8]
 [7 4 8 1 1]
 [7 4 1 8 7]
 [5 2 3 3 8]
 [5 1 1 5 0]]
[21 21 27 21 12]
