# Flatten, Ravel, Transpose & Resize

Warn-up

In [8]:
import numpy as np 
sales=np.arange(101,137)
print("Sales data: \n",sales)

Sales data: 
 [101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136]


In [16]:
# 1. Reshape the array into 6x6 matrix and find the sum of the third row.
sales6x6=sales.reshape(6,6)
sum_of_3R=sales6x6[2,:]
print("Reshaped Sales Array: \n",sales6x6)
print("Element of third row: \n",sum_of_3R)
print("Sum of 3rd row elements: ",sum_of_3R.sum())

Reshaped Sales Array: 
 [[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]
 [125 126 127 128 129 130]
 [131 132 133 134 135 136]]
Element of third row: 
 [113 114 115 116 117 118]
Sum of 3rd row elements:  693


In [17]:
# Reshape the array into a 4x9 matrix and find the largest value in the second column.
sales4x9=sales.reshape(4,9)
second_column_ele=sales4x9[:,1]
print("Reshaped Sales Array: \n",sales4x9)
print("Elements of Second Column are : ",second_column_ele)
print("Largest values in Second column: ",second_column_ele.max())

Reshaped Sales Array: 
 [[101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118]
 [119 120 121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134 135 136]]
Elements of Second Column are :  [102 111 120 129]
Largest values in Second column:  129


In [18]:
# Transpose the 6x6 matrix and find the sum of its last row.
transpose6x6=np.transpose(sales6x6)
tranpose_lrow=transpose6x6[-1,:]
print("Transpose Array: \n",transpose6x6)
print("Last Row of transposed Array: ",tranpose_lrow)
print("Sum of Last row of T Array: ",tranpose_lrow.sum())

Transpose Array: 
 [[101 107 113 119 125 131]
 [102 108 114 120 126 132]
 [103 109 115 121 127 133]
 [104 110 116 122 128 134]
 [105 111 117 123 129 135]
 [106 112 118 124 130 136]]
Last Row of transposed Array:  [106 112 118 124 130 136]
Sum of Last row of T Array:  726


In [20]:
# Flatten the 6x6 matrix and extract the last 8 elements.
flat=sales6x6.flatten()
print("Last 8 element after flatten: ",flat[-8:])

Last 8 element after flatten:  [129 130 131 132 133 134 135 136]


In [ ]:
# Ravel the 6x6 matrix and find the average of elements from index 10 to 20.
ravel=sales6x6.ravel()
elements=ravel[10:21]
print("Elements from index 10 to 20 are: ",elements)
print("Average of these elements: ",elements.mean())

Elements from index 10 to 20 are:  [111 112 113 114 115 116 117 118 119 120 121]
Average of these elements:  116.0


Moderate

In [ ]:
sales=np.arange(101,137) # The data represents sales of 6 stores(cols) over 6 days(row)

In [27]:
# Reshape appropriately and find the store with the highest total sales.
daysXstores=sales.reshape(6,6)
sales_per_store=daysXstores.sum(axis=0)
print("Sales(DaysXStores)\n:",daysXstores)
print("Sales per Store: ",sales_per_store)
print("Store with highest total sales is at index ",np.argmax(sales_per_store)," with highest sales of ",sales_per_store.max())


Sales(DaysXStores)
: [[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]
 [125 126 127 128 129 130]
 [131 132 133 134 135 136]]
Sales per Store:  [696 702 708 714 720 726]
Store with highest total sales is at index  5  with highest sales of  726


In [28]:
# Find the day with the highest overall sales.
sales_per_day=daysXstores.sum(axis=1)
print("Sales per Day: ",sales_per_day)
print("Store with highest total sales is at index ",np.argmax(sales_per_day),"with highest sales of ",sales_per_day.max())

Sales per Day:  [621 657 693 729 765 801]
Store with highest total sales is at index  5 with highest sales of  801


In [ ]:
# Extract the sales of Store 4 during the last three days.
store4SalesL3D=daysXstores[-3:,3]
print("Sales of store 4 during the last three days: ",store4SalesL3D)

Sales of store 4 during the last three days:  [122 128 134]


In [32]:
# Find the difference between the best and worst performing store.
best=sales_per_store.max()
worst=sales_per_store.min()
print("The difference between the best and worst performed stores: ",best-worst)

The difference between the best and worst performed stores:  30


In [35]:
# Transpose the data and determine which day had the highest average sales.
TdaysXsales=np.transpose(daysXstores)
highest_avg_sales_perday=TdaysXsales.sum(axis=1)
print("Transpose Sales(Day X Sales):\n",TdaysXsales)
print("Highest average sales day at index ",np.argmax(highest_avg_sales_perday)," with highest sales of ",highest_avg_sales_perday.mean())

Transpose Sales(Day X Sales):
 [[101 107 113 119 125 131]
 [102 108 114 120 126 132]
 [103 109 115 121 127 133]
 [104 110 116 122 128 134]
 [105 111 117 123 129 135]
 [106 112 118 124 130 136]]
Highest average sales day at index  5  with highest sales of  711.0


Higher

In [36]:
matrix=np.arange(1,50)

In [43]:
# Resize the array into a 7x7 matrix and calculate the sum of both diagonals.
resized7x7=matrix.reshape(7,7)
dia_ele=np.diagonal(resized7x7)
anti_dia_ele=np.diagonal(np.fliplr(resized7x7))
print("Resized 7x7 Matrix is: \n",resized7x7)
print(f"Diagonal Elements: {dia_ele} , sum: {dia_ele.sum()}")
print(f"Anti-diagonal Elements: {anti_dia_ele} , sum: {anti_dia_ele.sum()}")

Resized 7x7 Matrix is: 
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]
Diagonal Elements: [ 1  9 17 25 33 41 49] , sum: 175
Anti-diagonal Elements: [ 7 13 19 25 31 37 43] , sum: 175


In [50]:
# Flatten the matrix and find the sum of all elements at prime-numbered indices.
flat=resized7x7.flatten()

def is_prime(n):
    if n<2:
        return False
    elif n==2:
        return True
    elif n%2==0:
        return False
    else:
        for i in range(3,int(n**0.5)+1,2):
            if n%i==0:
                return False
            return True
prime_idx=[i for i in range(len(flat)) if is_prime(i)]
prime_idx_ele=flat[prime_idx]
print("Prime Index Elements: ",prime_idx_ele)
print("Sum of Prime Index Elements: ",prime_idx_ele.sum())

Prime Index Elements:  [ 3 12 14 18 20 24 26 30 32 36 38 42 44 48]
Sum of Prime Index Elements:  387


In [52]:
# Transpose the matrix and calculate the difference between the largest row sum and smallest row sum. 
T7x7=np.transpose(resized7x7)
lar_row_sum=T7x7.sum(axis=1).max() 
sma_row_sum=T7x7.sum(axis=1).min() 
print("Transpose Matrix: \n",T7x7)
print("The difference between the largest row sum and smalles row sum: ",lar_row_sum-sma_row_sum)

Transpose Matrix: 
 [[ 1  8 15 22 29 36 43]
 [ 2  9 16 23 30 37 44]
 [ 3 10 17 24 31 38 45]
 [ 4 11 18 25 32 39 46]
 [ 5 12 19 26 33 40 47]
 [ 6 13 20 27 34 41 48]
 [ 7 14 21 28 35 42 49]]
The difference between the largest row sum and smalles row sum:  42


In [57]:
# Extract the border elements only and find their average.
top=T7x7[0,:]
bottom=T7x7[-1,:]
left=T7x7[1:-1,0]
right=T7x7[1:-1,-1]
print("Top border elements: ",top)
print("Bottom border elements: ",bottom)
print("Left border elements: ",left)
print("Right border elements: ",right)
border_element=np.concatenate((top,bottom,left,right))
print("All border elements: ",border_element)
print("Average of border element: ",border_element.mean())

Top border elements:  [ 1  8 15 22 29 36 43]
Bottom border elements:  [ 7 14 21 28 35 42 49]
Left border elements:  [2 3 4 5 6]
Right border elements:  [44 45 46 47 48]
All border elements:  [ 1  8 15 22 29 36 43  7 14 21 28 35 42 49  2  3  4  5  6 44 45 46 47 48]
Average of border element:  25.0


In [60]:
# Find the sum of all elements in the center 3x3 block.
center3x3=resized7x7[2:5,2:5]
print("Center 3x3 Block: \n",center3x3,"\nSum: ",center3x3.sum())


Center 3x3 Block: 
 [[17 18 19]
 [24 25 26]
 [31 32 33]] 
Sum:  225
