# Given a dataset of 8 student exam records(name_id,math,dsa,statistics)

In [2]:
import numpy as np 
students = np.array([
    [101, 88, 76, 91],
    [102, 72, 85, 68],
    [103, 95, 90, 87],
    [104, 60, 70, 75],
    [105, 83, 78, 88],
    [106, 91, 95, 92],
    [107, 55, 62, 70],
    [108, 78, 80, 85]
])
print("Students Data: \n",students)

Students Data: 
 [[101  88  76  91]
 [102  72  85  68]
 [103  95  90  87]
 [104  60  70  75]
 [105  83  78  88]
 [106  91  95  92]
 [107  55  62  70]
 [108  78  80  85]]


In [ ]:
# Split the data into two batches of 4 students each.
batch1,batch2=np.vsplit(students,2)
print("First Batch Student Info: \n",batch1)
print("Second Batch Students Info: \n",batch2)

First Batch Student Info: 
 [[101  88  76  91]
 [102  72  85  68]
 [103  95  90  87]
 [104  60  70  75]]
Second Batch Students Info: 
 [[105  83  78  88]
 [106  91  95  92]
 [107  55  62  70]
 [108  78  80  85]]


In [12]:
# From batch1, select only students who scored above 80 in math.
filtered_batch1=batch1[batch1[:,1]>80]
print("First batch students with marks above 80 in math are: ",filtered_batch1[:,0])

First batch students with marks above 80 in math are:  [101 103]


In [13]:
# From batch2, select only students who scored above 80 in statistics.
filtered_batch2=batch2[batch2[:,3]>80]
print("Second batch students with marks above 80 in statistics are: ",filtered_batch2[:,0])

Second batch students with marks above 80 in statistics are:  [105 106 108]


In [16]:
# Join both filtered results back into one array.
filtered_students=np.vstack([filtered_batch1,filtered_batch2])
print("Filtered Students' info: \n",filtered_students)

Filtered Students' info: 
 [[101  88  76  91]
 [103  95  90  87]
 [105  83  78  88]
 [106  91  95  92]
 [108  78  80  85]]
