# Given a dataset of 8 student exam records(name_id,math,dsa,statistics)

In [2]:
import numpy as np 
students = np.array([
    [101, 88, 76, 91],
    [102, 72, 85, 68],
    [103, 95, 90, 87],
    [104, 60, 70, 75],
    [105, 83, 78, 88],
    [106, 91, 95, 92],
    [107, 55, 62, 70],
    [108, 78, 80, 85]
])
print("Students Data: \n",students)

Students Data: 
 [[101  88  76  91]
 [102  72  85  68]
 [103  95  90  87]
 [104  60  70  75]
 [105  83  78  88]
 [106  91  95  92]
 [107  55  62  70]
 [108  78  80  85]]


In [ ]:
# Split the data into two batches of 4 students each.
batch1,batch2=np.vsplit(students,2)
print("First Batch Student Info: \n",batch1)
print("Second Batch Students Info: \n",batch2)

First Batch Student Info: 
 [[101  88  76  91]
 [102  72  85  68]
 [103  95  90  87]
 [104  60  70  75]]
Second Batch Students Info: 
 [[105  83  78  88]
 [106  91  95  92]
 [107  55  62  70]
 [108  78  80  85]]


In [12]:
# From batch1, select only students who scored above 80 in math.
filtered_batch1=batch1[batch1[:,1]>80]
print("First batch students with marks above 80 in math are: ",filtered_batch1[:,0])

First batch students with marks above 80 in math are:  [101 103]


In [13]:
# From batch2, select only students who scored above 80 in statistics.
filtered_batch2=batch2[batch2[:,3]>80]
print("Second batch students with marks above 80 in statistics are: ",filtered_batch2[:,0])

Second batch students with marks above 80 in statistics are:  [105 106 108]


In [16]:
# Join both filtered results back into one array.
filtered_students=np.vstack([filtered_batch1,filtered_batch2])
print("Filtered Students' info: \n",filtered_students)

Filtered Students' info: 
 [[101  88  76  91]
 [103  95  90  87]
 [105  83  78  88]
 [106  91  95  92]
 [108  78  80  85]]


# Daily Temperature readings for 4(each row->1 week, each col-> 1day)

In [17]:
temps = np.array([
    [32, 35, 33, 30, 28, 31, 34],
    [29, 27, 30, 33, 35, 36, 34],
    [31, 33, 34, 36, 38, 37, 35],
    [28, 26, 29, 31, 30, 32, 33]
])

In [19]:
# Split into individual weeks
week1,week2,week3,week4=np.vsplit(temps,4)
print("First week temperature readings: ",week1)
print("Second week temperature readings: ",week2)
print("Third week temperature readings: ",week3)
print("Fourth week temperature readings: ",week4)

First week temperature readings:  [[32 35 33 30 28 31 34]]
Second week temperature readings:  [[29 27 30 33 35 36 34]]
Third week temperature readings:  [[31 33 34 36 38 37 35]]
Fourth week temperature readings:  [[28 26 29 31 30 32 33]]


In [20]:
# Reshape each week into a (7,1) column vector.
rweek1=week1.reshape(7,1)
rweek2=week2.reshape(7,1)
rweek3=week3.reshape(7,1)
rweek4=week4.reshape(7,1)
print("First week temp readings: \n",rweek1)
print("Second week temp readings: \n",rweek2)
print("Second week temp readings: \n",rweek3)
print("Second week temp readings: \n",rweek4)

First week temp readings: 
 [[32]
 [35]
 [33]
 [30]
 [28]
 [31]
 [34]]
Second week temp readings: 
 [[29]
 [27]
 [30]
 [33]
 [35]
 [36]
 [34]]
Second week temp readings: 
 [[31]
 [33]
 [34]
 [36]
 [38]
 [37]
 [35]]
Second week temp readings: 
 [[28]
 [26]
 [29]
 [31]
 [30]
 [32]
 [33]]


In [21]:
# Horizontally stack all 4 columns vectors in order that each column represent a week.
stacked_readings=np.hstack([rweek1,rweek2,rweek3,rweek4])
print("Temperature Readings(Days X Week):\n",stacked_readings)

Temperature Readings(Days X Week):
 [[32 29 31 28]
 [35 27 33 26]
 [33 30 34 29]
 [30 33 36 31]
 [28 35 38 30]
 [31 36 37 32]
 [34 34 35 33]]


In [26]:
# Find the hottest day of each week.
Tday1=stacked_readings[:,0]
Tday2=stacked_readings[:,1]
Tday3=stacked_readings[:,2]
Tday4=stacked_readings[:,3]
print(f"Hottest Day of first week is Day{np.argmax(Tday1)+1} with temperature of {Tday1.max()}C.")
print(f"Hottest Day of second week is Day{np.argmax(Tday2)+1} with temperature of {Tday2.max()}C.")
print(f"Hottest Day of third week is Day{np.argmax(Tday3)+1} with temperature of {Tday3.max()}C.")
print(f"Hottest Day of fourth week is Day{np.argmax(Tday4)+1} with temperature of {Tday4.max()}C.")

Hottest Day of first week is Day2 with temperature of 35C.
Hottest Day of second week is Day6 with temperature of 36C.
Hottest Day of third week is Day5 with temperature of 38C.
Hottest Day of fourth week is Day7 with temperature of 33C.


# Two arrays -> one with product IDs and one with prices.

In [ ]:
product_ids = np.array([[101], [102], [103], [104], [105]])
prices       = np.array([[25.5], [40.0], [15.75], [60.0], [33.25]])

In [29]:
# Join them into a single (5,2) array.
sales=np.hstack([product_ids,prices])
print("Sales Details: \n",sales)

Sales Details: 
 [[101.    25.5 ]
 [102.    40.  ]
 [103.    15.75]
 [104.    60.  ]
 [105.    33.25]]


In [35]:
# Split the result into two groups: products with price below 35 and products at or above 35.
group1,group2=sales[sales[:,1]>35],sales[sales[:,1]<=35]
print("Group1 with product price above 35 are: \n",group1)
print("Group2 with product price equal or below 35 are: \n",group2)

Group1 with product price above 35 are: 
 [[102.  40.]
 [104.  60.]]
Group2 with product price equal or below 35 are: 
 [[101.    25.5 ]
 [103.    15.75]
 [105.    33.25]]


In [38]:
# Return the products IDs of the expensive group.
group1_sales=group1[:,1].sum()
group2_sales=group2[:,1].sum()
def getIDs(group1_sales,group2_sales):
    if group1_sales>group2_sales:
        print("Expensive group products IDs are: ",group1[0,:])
    else: 
        print("Expensive group products IDs are: ",group2[0,:])
getIDs(group1_sales,group2_sales)
    

Expensive group products IDs are:  [102.  40.]
