# Column Broadcasting

In [2]:
import numpy as np 
matrix=np.arange(1,10,1).reshape(3,3)
col=np.array([[10],[20],[30]])

In [3]:
# Add column to matrix.
print(matrix+col)

[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [4]:
# Multiply matrix by col.
print(matrix * col)

[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


In [5]:
# Subtract col from matrix.
print(matrix-col)

[[ -9  -8  -7]
 [-16 -15 -14]
 [-23 -22 -21]]


In [6]:
# Divide matrix by col.
print(matrix/col)

[[0.1        0.2        0.3       ]
 [0.2        0.25       0.3       ]
 [0.23333333 0.26666667 0.3       ]]


Explain why Broadcasting works here.
-> For broadcasting compatibility is required and to be compatible either both arrays must be of same dimesion or one of the dimesion is 1.

# For the compatibility of 1D array either they have the same length or one of the has length 1