# Load or create a 2D dataset of 10 students x 5 test scores. Then in sequence:

In [1]:
import numpy as np 
scores=np.random.randint(15,100,50).reshape(10,5) # row represents student and col represents test scores
print("Student Scores(Student x Scores):\n",scores)

Student Scores(Student x Scores):
 [[45 91 51 64 92]
 [67 64 59 34 21]
 [56 16 29 91 43]
 [42 83 35 85 69]
 [91 85 98 16 60]
 [62 16 23 25 42]
 [63 43 39 63 38]
 [67 52 98 21 80]
 [16 60 31 15 20]
 [47 50 94 65 48]]


1. Find the total scores according to test subjects.

In [2]:
print("Total Scores Test: ",scores.sum(axis=1))

Total Scores Test:  [343 245 235 314 350 168 246 318 142 304]


2. Clip all scores to range[30,100]

In [3]:
print("Clipped Scores: \n",np.clip(scores,30,100))

Clipped Scores: 
 [[45 91 51 64 92]
 [67 64 59 34 30]
 [56 30 30 91 43]
 [42 83 35 85 69]
 [91 85 98 30 60]
 [62 30 30 30 42]
 [63 43 39 63 38]
 [67 52 98 30 80]
 [30 60 31 30 30]
 [47 50 94 65 48]]


3. Flag all scores below the 25th percentile using np.where().

In [4]:
q1=np.percentile(scores,25)
print("Result: \n",np.where(scores<q1,"FLAGGED",scores))

Result: 
 [['45' '91' '51' '64' '92']
 ['67' '64' '59' 'FLAGGED' 'FLAGGED']
 ['56' 'FLAGGED' 'FLAGGED' '91' '43']
 ['42' '83' '35' '85' '69']
 ['91' '85' '98' 'FLAGGED' '60']
 ['62' 'FLAGGED' 'FLAGGED' 'FLAGGED' '42']
 ['63' '43' '39' '63' '38']
 ['67' '52' '98' 'FLAGGED' '80']
 ['FLAGGED' '60' 'FLAGGED' 'FLAGGED' 'FLAGGED']
 ['47' '50' '94' '65' '48']]


4. Find the IQR accross the full dataset.

In [6]:
q2=np.percentile(scores,75)
IQR=q2-q1
print("Interquartile Range: ",IQR)

Interquartile Range:  32.75
