# Row Broadcasting

In [2]:
import numpy as np 
matrix=np.arange(1,10,1).reshape(3,3)
row=np.array([10,20,30])

In [3]:
# Add row to matrix.
print(matrix+row)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [4]:
# Subtract row from matrix.
print(matrix-row)

[[ -9 -18 -27]
 [ -6 -15 -24]
 [ -3 -12 -21]]


In [6]:
# Multiply matrix by row
print(matrix*row)

[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [7]:
# Divide matrix by row.
print(matrix/row)

[[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]
 [0.7  0.4  0.3 ]]


In [ ]:
# Find the resulting shape after broadcasting.
# the row's shape doesn't permanently changes. It's just temporarily expanded during the operation.

[10 20 30]
