# Slicing 1D Arrays

In [1]:
import numpy as np 
arr=np.arange(5,51,5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


In [2]:
# Exract the first five elements.
print(arr[:5])

[ 5 10 15 20 25]


In [7]:
# Extract the last four elements.
print(arr[-4:])

[35 40 45 50]


In [8]:
# Extract every second element.
print(arr[1::2])

[10 20 30 40 50]


In [11]:
# Reverse the array using slicing.
print(arr[::-1])

[50 45 40 35 30 25 20 15 10  5]


In [12]:
# Extract only odd-indexed elements.
print(arr[1::2])

[10 20 30 40 50]


In [13]:
# Extract only even-indexed elements.
print(arr[::2])

[ 5 15 25 35 45]


In [15]:
# Extract [20,25,30,35]
print(arr[3:7])

[20 25 30 35]
