# Axis Operations

In [ ]:
import numpy as np 
marks=np.array([[80,70,90],[60,85,75],[95,88,92]]) # (student,subjects)
print(marks)

[[80 70 90]
 [60 85 75]
 [95 88 92]]


In [5]:
# Find each student's total marks.
print("Total marks of each student:",marks.sum(axis=1))


Total marks of each student: [240 220 275]


In [4]:
# Find each subject's total marks.
print("Total marks per subject: ",marks.sum(axis=0))

Total marks per subject:  [235 243 257]


In [10]:
# Which student performed best overall?
total_marks=marks.sum(axis=1)
print("Student who performed best overall is student with total marks: ",total_marks.max())


Student who performed best overall is student with total marks:  275
