# Preprocessing a dataset for a machine learning pipeline:

In [1]:
import numpy as np 
np.random.seed(0)
dataset = np.random.randint(1, 100, size=(8, 5))
print("Datasets: \n",dataset)

Datasets: 
 [[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]
 [10 21 81 70 80]
 [48 65 83 89 50]
 [30 20 20 15 40]]


In [5]:
# Split into train(6) and test(2).
train,test=np.vsplit(dataset,[6])
print("Train datasets: \n",train)
print("Test datasets: \n",test)

Train datasets: 
 [[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]
 [10 21 81 70 80]]
Test datasets: 
 [[48 65 83 89 50]
 [30 20 20 15 40]]


In [10]:
# Normalize the train set by subtracting its mean and dividing by its std - do this on a copy so the original dataset is preserved
trainMean=train.mean()
trainStd=train.std()
print("Train dataset mean: ",np.round(trainMean,2))
print("Train dataset standard deviation: ",np.round(trainStd),2)
trainsetCpy=train.copy()
normalizedTrainset=np.round((train-trainMean)/trainStd,2)
print("Original Train Datasets:\n ",train)
print("Normalized Train Datasets:\n ",normalizedTrainset)

Train dataset mean:  58.17
Train dataset standard deviation:  26.0 2
Original Train Datasets:
  [[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]
 [10 21 81 70 80]]
Normalized Train Datasets:
  [[-0.51 -0.39  0.26  0.38  0.38]
 [-1.86  1.   -1.4  -0.82  1.15]
 [ 0.5   1.19  1.19 -1.75  0.03]
 [ 0.3  -0.7   1.15 -0.43  1.19]
 [ 0.92 -0.78 -1.24  0.77  0.57]
 [-1.86 -1.44  0.88  0.46  0.84]]


In [12]:
# Verify the original is unchanged using np.shares_memory()
print("Is changed? : ",np.shares_memory(normalizedTrainset,train)) # as we have changed the train data if they both had referred to same memory, the data would had modified in original set also.


Is changed? :  False
