# Preprocessing a dataset for a machine learning pipeline:

In [1]:
import numpy as np 
np.random.seed(0)
dataset = np.random.randint(1, 100, size=(8, 5))
print("Datasets: \n",dataset)

Datasets: 
 [[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]
 [10 21 81 70 80]
 [48 65 83 89 50]
 [30 20 20 15 40]]


In [5]:
# Split into train(6) and test(2).
train,test=np.vsplit(dataset,[6])
print("Train datasets: \n",train)
print("Test datasets: \n",test)

Train datasets: 
 [[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]
 [10 21 81 70 80]]
Test datasets: 
 [[48 65 83 89 50]
 [30 20 20 15 40]]


In [10]:
# Normalize the train set by subtracting its mean and dividing by its std - do this on a copy so the original dataset is preserved
trainMean=train.mean()
trainStd=train.std()
print("Train dataset mean: ",np.round(trainMean,2))
print("Train dataset standard deviation: ",np.round(trainStd),2)
trainsetCpy=train.copy()
normalizedTrainset=np.round((train-trainMean)/trainStd,2)
print("Original Train Datasets:\n ",train)
print("Normalized Train Datasets:\n ",normalizedTrainset)

Train dataset mean:  58.17
Train dataset standard deviation:  26.0 2
Original Train Datasets:
  [[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]
 [10 21 81 70 80]]
Normalized Train Datasets:
  [[-0.51 -0.39  0.26  0.38  0.38]
 [-1.86  1.   -1.4  -0.82  1.15]
 [ 0.5   1.19  1.19 -1.75  0.03]
 [ 0.3  -0.7   1.15 -0.43  1.19]
 [ 0.92 -0.78 -1.24  0.77  0.57]
 [-1.86 -1.44  0.88  0.46  0.84]]


In [12]:
# Verify the original is unchanged using np.shares_memory()
print("Is changed? : ",np.shares_memory(normalizedTrainset,train)) # as we have changed the train data if they both had referred to same memory, the data would had modified in original set also.


Is changed? :  False


# Received sensor readings and need to apply corrections without losing raw data:

In [13]:
readings = np.array([
    [1.02, 0.98, 1.05, 0.97],
    [1.10, 1.03, 0.95, 1.08],
    [0.93, 1.07, 1.02, 0.99],
    [1.05, 0.96, 1.08, 1.01]
])

In [14]:
# Create a working copy of readings.
data=readings.copy()
print("Copy readings data: \n",data)

Copy readings data: 
 [[1.02 0.98 1.05 0.97]
 [1.1  1.03 0.95 1.08]
 [0.93 1.07 1.02 0.99]
 [1.05 0.96 1.08 1.01]]


In [15]:
# On the copy, clip all values to the range [0.95,1.05]
clipped_data=np.clip(data,0.95,1.05)
print("Clippled data readings: \n",clipped_data)

Clippled data readings: 
 [[1.02 0.98 1.05 0.97]
 [1.05 1.03 0.95 1.05]
 [0.95 1.05 1.02 0.99]
 [1.05 0.96 1.05 1.01]]


In [16]:
# Reshape the clipped copy into shape(2,8)
reshaped_data=clipped_data.reshape(2,8)
print("Reshaped clipped data: \n",reshaped_data)

Reshaped clipped data: 
 [[1.02 0.98 1.05 0.97 1.05 1.03 0.95 1.05]
 [0.95 1.05 1.02 0.99 1.05 0.96 1.05 1.01]]


In [19]:
# Verify the original is completely untouched.
print("Is data copy of original?: ",np.shares_memory(readings,data))
print("Is a copy?: ",data.base is None)
# The shares memory varifies that data has copy of readings. So it is not possible to modify readings dataset by modifying data.
# Also, data is not referencing to readings.

Is data copy of original?:  False
Is a copy?:  True


# Managing a sales pipeline. Raw data comes in as a combined array of 10 sales records, each with [sales_rep_id,region_code,q1_sales,q2_sales]:

In [20]:
raw = np.array([
    [201, 1, 15000, 17000],
    [202, 2, 12000, 13500],
    [203, 1, 18500, 21000],
    [204, 3, 9800,  11000],
    [205, 2, 22000, 19500],
    [206, 1, 13000, 14500],
    [207, 3, 17500, 16000],
    [208, 2, 11000, 12500],
    [209, 1, 20000, 23000],
    [210, 3, 8500,  9000 ]
])

In [21]:
# Make a copy of raw to work on - keep raw untouched as the source of truth.
copy=raw.copy()
print("Copied Sales data: \n",copy)

Copied Sales data: 
 [[  201     1 15000 17000]
 [  202     2 12000 13500]
 [  203     1 18500 21000]
 [  204     3  9800 11000]
 [  205     2 22000 19500]
 [  206     1 13000 14500]
 [  207     3 17500 16000]
 [  208     2 11000 12500]
 [  209     1 20000 23000]
 [  210     3  8500  9000]]


In [22]:
# Split the working copy into two halves(first 5, last 5)
Fhalf,Lhalf=np.vsplit(copy,2)
print("First half sales data:\n",Fhalf)
print("Last half sales data:\n",Lhalf)

First half sales data:
 [[  201     1 15000 17000]
 [  202     2 12000 13500]
 [  203     1 18500 21000]
 [  204     3  9800 11000]
 [  205     2 22000 19500]]
Last half sales data:
 [[  206     1 13000 14500]
 [  207     3 17500 16000]
 [  208     2 11000 12500]
 [  209     1 20000 23000]
 [  210     3  8500  9000]]


In [27]:
# On each half, use Boolean indexing to find records where both q1 and q2 sales exceed 13000.
FhalfExcSales=Fhalf[(Fhalf[:,2]>13000)&(Fhalf[:,3]>13000)]
print("Records with q1 and q1 sales over 13000$ in first half data: \n",FhalfExcSales)

LhalfExcSales=Lhalf[(Lhalf[:,2]>13000)&(Lhalf[:,3]>13000)]
print("Records with q1 and q1 sales over 13000$ in second half data: \n",LhalfExcSales)

Records with q1 and q1 sales over 13000$ in first half data: 
 [[  201     1 15000 17000]
 [  203     1 18500 21000]
 [  205     2 22000 19500]]
Records with q1 and q1 sales over 13000$ in second half data: 
 [[  207     3 17500 16000]
 [  209     1 20000 23000]]


In [56]:
# Stack the qualifying records from both halves into one filtered array.
Filtered_arr=np.vstack([FhalfExcSales,LhalfExcSales])
print("Filtered Array: \n",Filtered_arr)

Filtered Array: 
 [[  201     1 15000 17000]
 [  203     1 18500 21000]
 [  205     2 22000 19500]
 [  207     3 17500 16000]
 [  209     1 20000 23000]]


In [57]:
# Add a new column to the filterd array representing total sales(q1+q2)
total_sales = Filtered_arr[:,2:].sum(axis=1).reshape(-1, 1)
Filtered_arr = np.hstack([Filtered_arr, total_sales])

print("Filtered Array with Total Sales:\n", Filtered_arr)


Filtered Array with Total Sales:
 [[  201     1 15000 17000 32000]
 [  203     1 18500 21000 39500]
 [  205     2 22000 19500 41500]
 [  207     3 17500 16000 33500]
 [  209     1 20000 23000 43000]]
