# Reshape(.reshape())

In [2]:
import numpy as np 
arr=np.arange(1,25)
print("Orginal Array: ",arr)

Orginal Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [8]:
# Reshape the array so that the last row becomes: [21 22 23 24]
new_arr=arr.reshape(6,4)
print("Reshaped Array: \n",new_arr)

Reshaped Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [10]:
# After reshaping, extract: [7 8 9 10]
print("Extracted Elements: ",new_arr[[1,1,2,2],[2,3,0,1]])

Extracted Elements:  [ 7  8  9 10]


In [11]:
# Reshape the array so that element 15 is located at index 2 and column index 2.
reshaped_arr=arr.reshape(4,6)
print("Reshaped Array so that arr[2][2]=15: \n",reshaped_arr)

Reshaped Array so that arr[2][2]=15: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [3]:
array=np.arange(1,37)

In [13]:
# Reshape the array into a matrix and find the sum of the middle row.
matrix=array.reshape(9,4);
print("Reshaped Array: \n",matrix)
mid_rowIdx=len(matrix)//2
print("Sum of middle row: ",matrix[mid_rowIdx].sum())


Reshaped Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]]
Sum of middle row:  74


In [15]:
# Reshape the array again into 6 x 6 matrix and extract the border elements only.
reshaped=array.reshape(6,6)
print("Reshaped Array: \n",reshaped)

top=reshaped[0,:]
bottom=reshaped[-1,:]
left=reshaped[1:-1,0]
right=reshaped[1:-1,-1]

print("Top border element: ",top)
print("Botton border elements: ",bottom)
print("Left border element: ",left)
print("Right border elements: ",right)

Reshaped Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Top border element:  [1 2 3 4 5 6]
Botton border elements:  [31 32 33 34 35 36]
Left border element:  [ 7 13 19 25]
Right border elements:  [12 18 24 30]


In [17]:
# Calculate the sum of both diagonals.
print("Diagonal element sum : ",reshaped.trace())
print("Anti-Diagonal element sum: ",np.fliplr(reshaped).trace())

Diagonal element sum :  111
Anti-Diagonal element sum:  111
