# Reshape(.reshape())

In [1]:
import numpy as np 
arr=np.arange(1,25)
print("Orginal Array: ",arr)

Orginal Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [8]:
# Reshape the array so that the last row becomes: [21 22 23 24]
new_arr=arr.reshape(6,4)
print("Reshaped Array: \n",new_arr)

Reshaped Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [10]:
# After reshaping, extract: [7 8 9 10]
print("Extracted Elements: ",new_arr[[1,1,2,2],[2,3,0,1]])

Extracted Elements:  [ 7  8  9 10]


In [11]:
# Reshape the array so that element 15 is located at index 2 and column index 2.
reshaped_arr=arr.reshape(4,6)
print("Reshaped Array so that arr[2][2]=15: \n",reshaped_arr)

Reshaped Array so that arr[2][2]=15: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
