# arange() & linspace()

In [1]:
# Create an array containing number from 0 to 19 using arange().
import numpy as np 
nums=np.arange(1,20,1)
print(nums)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [2]:
# Create an array containing even numbers from 2 to 20.
even_nums=np.arange(2,22,2)
print(even_nums)

[ 2  4  6  8 10 12 14 16 18 20]


In [4]:
# Create an array from 5 to 50 with a step size of 5.
nums=np.arange(5,55,5)
print(nums)

[ 5 10 15 20 25 30 35 40 45 50]


In [5]:
# Create an array of decimal values from 0 to 1 with a tep size of 0.2
nums=np.arange(0,1,0.2)
print(nums)

[0.  0.2 0.4 0.6 0.8]


In [6]:
# Generate 50 equal spaced values between -1 to 1.
values=np.linspace(-1,1,50)
print(values)

[-1.         -0.95918367 -0.91836735 -0.87755102 -0.83673469 -0.79591837
 -0.75510204 -0.71428571 -0.67346939 -0.63265306 -0.59183673 -0.55102041
 -0.51020408 -0.46938776 -0.42857143 -0.3877551  -0.34693878 -0.30612245
 -0.26530612 -0.2244898  -0.18367347 -0.14285714 -0.10204082 -0.06122449
 -0.02040816  0.02040816  0.06122449  0.10204082  0.14285714  0.18367347
  0.2244898   0.26530612  0.30612245  0.34693878  0.3877551   0.42857143
  0.46938776  0.51020408  0.55102041  0.59183673  0.63265306  0.67346939
  0.71428571  0.75510204  0.79591837  0.83673469  0.87755102  0.91836735
  0.95918367  1.        ]


In [ ]:
# Create an array fo 100 equally spaced values between 0 to 2pi.
import math
arr=np.linspace(0,2*np.pi,100)

NameError: name 'Math' is not defined