# Mini Real-World Challenge

In [2]:
import numpy as np 
revenue=np.arange(1000,1096)

A company has:
   * 8 branches
   * 12 months of revenue data

In [3]:
# Reshape the data appropriately.
branchXmonths=revenue.reshape(8,12)
print("Revenue Table(Branch X Months):\n",branchXmonths)

Revenue Table(Branch X Months):
 [[1000 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011]
 [1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023]
 [1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035]
 [1036 1037 1038 1039 1040 1041 1042 1043 1044 1045 1046 1047]
 [1048 1049 1050 1051 1052 1053 1054 1055 1056 1057 1058 1059]
 [1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071]
 [1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083]
 [1084 1085 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095]]


In [4]:
# Find the best-performing branch.
#  The best-performing branch will be the branch with the highest revenue.
gross_revenue_per_branch=branchXmonths.sum(axis=1)
print("The total revenue per branch: ",gross_revenue_per_branch)
print(f"The best-performing branch is Branch {np.argmax(gross_revenue_per_branch)+1} with total revenue of {gross_revenue_per_branch.max()}$")


The total renveue per branch:  [12066 12210 12354 12498 12642 12786 12930 13074]
The best-performing branch is Branch 8 with total revenue of 13074$


In [5]:
# Find the best-performing month.
gross_revenue_per_month=branchXmonths.sum(axis=0)
print("The total revenue per branch: ",gross_revenue_per_month)
print(f"The best-performing is {np.argmax(gross_revenue_per_month)+1}th Month with total revenue of {gross_revenue_per_month.max()}$")


The total renveue per branch:  [8336 8344 8352 8360 8368 8376 8384 8392 8400 8408 8416 8424]
The best-performing is 12th Month with total revenue of 8424$


In [12]:
# Find the month with the lowest average revenue.
avg_revenue_month=branchXmonths.mean(axis=0)
print(f"The month with lowest average revenue is {np.argmin(avg_revenue_month)+1}th month with the average revenue of {avg_revenue_month.min()}")

The month with lowest average revenue is 1th month with the average revenue of 1042.0


In [43]:
# Transpose the dataset and identify the month-to-month revenue trend.
monthXbranch=np.transpose(branchXmonths)

# Suffle to imitate real-world data
flat=monthXbranch.ravel()
np.random.shuffle(flat)
monthXbranch=flat.ravel().reshape(monthXbranch.shape)

total_revenue_per_month=monthXbranch.sum(axis=1)
revenue_diff_per_month=np.diff(total_revenue_per_month)
percentage_change=(revenue_diff_per_month/total_revenue_per_month[:-1])*100

print(f"Revenue dataset: \n{monthXbranch}")
print(f"Total revenue for each month across all branches: ",total_revenue_per_month)
print(f"Revenue difference across all branches within adjecent month: ",revenue_diff_per_month)
print(f"Percentage change in revenue across all branches within adjecent month: ",np.round(percentage_change,2))


Revenue dataset: 
[[1030 1032 1056 1004 1084 1078 1063 1048]
 [1053 1045 1043 1065 1077 1017 1058 1071]
 [1051 1040 1070 1036 1054 1023 1020 1057]
 [1076 1066 1016 1081 1024 1038 1027 1046]
 [1064 1092 1049 1094 1090 1015 1001 1029]
 [1062 1073 1079 1082 1061 1047 1034 1088]
 [1059 1019 1025 1011 1035 1042 1002 1085]
 [1091 1068 1003 1028 1052 1083 1041 1012]
 [1009 1093 1069 1007 1013 1074 1067 1014]
 [1087 1080 1037 1044 1086 1050 1008 1060]
 [1026 1089 1055 1072 1006 1095 1039 1000]
 [1033 1005 1010 1022 1018 1075 1021 1031]]
Total revenue for each month across all branches:  [8395 8429 8351 8374 8434 8526 8278 8378 8346 8452 8382 8215]
Revenue difference across all branches within adjecent month:  [  34  -78   23   60   92 -248  100  -32  106  -70 -167]
Percentage change in revenue across all branches within adjecent month:  [ 0.41 -0.93  0.28  0.72  1.09 -2.91  1.21 -0.38  1.27 -0.83 -1.99]


In [ ]:
# Flatten the dataset and find the top 10 revenue values.
flat=np.sort(branchXmonths.flatten())
print("Revenues: \n",flat)

print("Top 10 revenue values: ",flat[-10:])


Revenues: 
 [1000 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013
 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027
 1028 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041
 1042 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055
 1056 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069
 1070 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083
 1084 1085 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095]
Top 10 revenue values:  [1086 1087 1088 1089 1090 1091 1092 1093 1094 1095]


In [48]:
# Calculate what percentage of revenues are above the overall average.
overall_avg=flat.mean()
revenues_above_overall_avg=flat[flat>overall_avg]

percentage_renvenue_above_avg=((revenues_above_overall_avg.size)/flat.size)*100

print(f"Revenues above overall average({overall_avg}): \n",revenues_above_overall_avg)
print(f"Percentage of revenues above the overall average is {np.round(percentage_renvenue_above_avg,2)}%")


Revenues above overall average(1047.5): 
 [1048 1049 1050 1051 1052 1053 1054 1055 1056 1057 1058 1059 1060 1061
 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1072 1073 1074 1075
 1076 1077 1078 1079 1080 1081 1082 1083 1084 1085 1086 1087 1088 1089
 1090 1091 1092 1093 1094 1095]
Percentage of revenues above the overall average is 50.0%


In [6]:
# Find the branch with the highest average revenue.
avg_revenue_branch=branchXmonths.mean(axis=1)
print(f"The branch with the highest average revenue is Branch {np.argmax(avg_revenue_branch)+1} with average revenue of {avg_revenue_branch.max()}$")

The branch with the highest average revenue is Branch 8 with average revenue of 1089.5$
