# A dataset of 5 houses with 3 features each(size,rooms,age):

In [2]:
import numpy as np
X = np.array([
    [1500, 3, 10],
    [2000, 4,  5],
    [1200, 2, 20],
    [1800, 3,  8],
    [2500, 5,  3]
], dtype=float)

In [3]:
# Analysis
max_size=X[:,0].max()
min_size=X[:,0].min()

max_rooms=X[:,1].max()
min_rooms=X[:,1].min()

max_age=X[:,2].max()
min_age=X[:,2].min()

print(f"Max House size: {max_size} sq. ft")
print(f"Min House size: {min_size} sq. ft")

print(f"Max Rooms: {max_rooms}")
print(f"Min Rooms: {min_rooms}")

print(f"Max House Age: {max_age} year(s)")
print(f"Min House Age: {min_age} year(s)")

Max House size: 2500.0 sq. ft
Min House size: 1200.0 sq. ft
Max Rooms: 5.0
Min Rooms: 2.0
Max House Age: 20.0 year(s)
Min House Age: 3.0 year(s)


In [8]:
# Normalize each feature column to range [0,1] using: (x-min)/(max-min)
X_norm=np.round((X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0)),4)
print(X_norm)

[[0.2308 0.3333 0.4118]
 [0.6154 0.6667 0.1176]
 [0.     0.     1.    ]
 [0.4615 0.3333 0.2941]
 [1.     1.     0.    ]]


In [11]:
# Compute the covariance matrix as (XnT & Xn)/(n-1) wher Xn is the normalized data.
XnT=np.transpose(X_norm)
X_cov=(np.dot(XnT,X_norm))/(len(X_norm)-1)
print("The Covariance matrix: \n",X_cov)

The Covariance matrix: 
 [[0.41124201 0.41025769 0.07578541]
 [0.41025769 0.41666667 0.0784201 ]
 [0.07578541 0.0784201  0.31747595]]


In [12]:
# Verify teh covariance matrix is symmetric by checking np.allclose(cov,cov.T)
X_covT=np.transpose(X_cov)
print("Is covarience matrix symmetric?: ",np.allclose(X_cov,X_covT))

Is covarience matrix symmetric?:  True


# A weight matrix for a neural network layer and an input batch:

In [13]:
np.random.seed(7)
W = np.random.randn(4, 3)   # 4 neurons, 3 input features
X = np.random.randn(5, 3)   # 5 samples, 3 features
b = np.array([0.5, -0.5, 0.3, 0.1])  # bias for each neuron

In [18]:
# Compute the forward pass: X @ W_T + b
W_T=np.transpose(W)
output=X @ W_T +b
print("Output: \n",output)

Output: 
 [[ 1.46803024 -0.0883936   0.511123    0.60853458]
 [-2.21107586 -1.52948483 -0.54577321 -1.14077146]
 [ 1.72942262  0.81956689  4.65823308  0.93637079]
 [ 1.00788564 -0.12749094  3.04408804  0.08672299]
 [ 1.08589952  0.62514126  2.43319821  1.04955838]]


In [23]:
# From the output, select only the rows(samples) where all newron values are positive.
selected_samples = output[(output > 0).all(axis=1)]
print(selected_samples)

[[1.72942262 0.81956689 4.65823308 0.93637079]
 [1.08589952 0.62514126 2.43319821 1.04955838]]


In [27]:
# Report how many samples passed that condition.
print(f"{selected_samples.shape[0]} samples that passed the previous condition. ")

2 samples that passed the previous condition. 


# A 4x4 matrix of quiz scores between students(entry[i,j]=score student i gave to student j):

In [28]:
scores = np.array([
    [0,  85, 90, 70],
    [80,  0, 75, 95],
    [88, 72,  0, 85],
    [91, 68, 82,  0]
])

In [ ]:
# Extract the upper traingle(excluding diagonal) - these are socres given by lower-numbered students and vice versa.
upr_matrix=np.triu(scores,k=1)
lwr_matrix=np.tril(scores,k=-1)
print("Scores of upper numbered students given by lowered ones: \n",upr_matrix)
print("Scores of lower numbered students given by upper ones: \n",lwr_matrix)


Scores of upper numbered students given by lowered ones: 
 [[ 0 85 90 70]
 [ 0  0 75 95]
 [ 0  0  0 85]
 [ 0  0  0  0]]
Scores of lower numbered students given by upper ones: 
 [[ 0  0  0  0]
 [80  0  0  0]
 [88 72  0  0]
 [91 68 82  0]]


In [36]:
# Compute the mean of each group and find the which group gave higher scores on average.
upr_mean=upr_matrix.mean()
lwr_mean=lwr_matrix.mean()
def result(mean,group):
    print(f"{group} Group gave higher socres on average(i.e. {mean})")
if upr_mean>lwr_mean :
    result(upr_mean,"Lower")
else:
    result(lwr_mean,"Upper")

Lower Group gave higher socres on average(i.e. 31.25)


# A system of 3 linear equations.
* 2x + y - z  = 8,
* 3x - y + 2z = -11,
* -2x + y + 2z = -3

In [37]:
A = np.array([[ 2,  1, -1],
              [-3, -1,  2],
              [-2,  1,  2]], dtype=float)

b = np.array([8., -11., -3.])

In [40]:
# Verify the systems has a unique solution by checking det(A).
det_A=np.linalg.det(A)
print("Determinant of A: ",det_A) 
if det_A!=0:
    print("Since the determinant of A doesn't equalt to zero so, the system has unique solution.")


Determinant of A:  -1.0
Since the determinant of A doesn't equalt to zero so, the system has unique solution.


In [45]:
# Solve using np.linalg.solve()
x=np.linalg.solve(A,b)
print("Value of x, y and z are: ",x)

Value of x, y and z are:  [ 2.  3. -1.]


In [48]:
# Verify the solution by computing A @ x and comparing to b using np.allclose().
cross=A @ x
print("Is A @ x and b equal?: ",np.allclose(cross,b))

Is A @ x and b equal?:  True
