# Fancy Indexing on 2D Arrays

In [2]:
import numpy as np 
arr=np.arange(1,10,1).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Extract elements [1,5,9]
print(arr[[0,1,2],[0,1,2]])

[1 5 9]


In [7]:
# Extract elements [3,5,7]
print(arr[[0,1,2],[2,1,0]])

[3 5 7]


In [10]:
# Extract elements[2,4,8]
print(arr[[0,1,2],[1,0,1]])

[2 4 8]


In [11]:
# Extract the first and third rows.
print(arr[[0,2]])

[[1 2 3]
 [7 8 9]]


In [15]:
# Extract the first and third columns.
print(arr[:,[0,2]])

[[1 3]
 [4 6]
 [7 9]]


In [16]:
# Create a new array containing [1,6,8] using row and column index arrays.
new_arr=arr[[0,1,2],[0,2,1]]
print(new_arr)

[1 6 8]
