# Generate 10 random floats between -5 and 5. Clip to [-1,1]. Plot the before/after using print to compare. 

In [5]:
import numpy as np 
arr=np.random.randint(-5,5,10)
clipped_arr=np.clip(arr,-1,1)
print("Before Clipping: ",arr)
print("After Clipping: ",clipped_arr)

Before Clipping:  [-3  0  0 -2 -4  3  0  2  4  4]
After Clipping:  [-1  0  0 -1 -1  1  0  1  1  1]


# You have a 2D image pixel array(values 0-255 but some went out of range due to brigntness adjustment). Clip it back to valid range and confirm with min() and max().

In [17]:
image=np.random.randint(0,300,49).reshape(7,7)
print("Unclipped Image:\n",image)
clipped_image=np.clip(image,0,255)
print("Clipped Image:\n",clipped_image)
print("Max : ",clipped_image.max())
print("Min : ",clipped_image.min())

Unclipped Image:
 [[ 71 124 135 252   0 171  74]
 [ 29  67 183 211 273 282  62]
 [232  29 181 291  57 164  20]
 [ 68 134  40 240 162 196 202]
 [ 53 160 173 202 158 176 210]
 [272 210 194  43  43  55 233]
 [121  48  20 224 166 124 227]]
Clipped Image:
 [[ 71 124 135 252   0 171  74]
 [ 29  67 183 211 255 255  62]
 [232  29 181 255  57 164  20]
 [ 68 134  40 240 162 196 202]
 [ 53 160 173 202 158 176 210]
 [255 210 194  43  43  55 233]
 [121  48  20 224 166 124 227]]
Max :  255
Min :  0


# Clip an array using only a lower bound(no upper limit). How do you pass the upper argument?

-> Pass arr.max() as upper argument

In [16]:
arr=np.random.randint(-50,100,15)
print("Before Clipping: ",arr)
lwr_clipped_arr=np.clip(arr,0,arr.max())
print("After Clipping lower bound: ",lwr_clipped_arr)

Before Clipping:  [ 42  13 -44  28  59 -35  96  98  59  89  48  47  83 -44  12]
After Clipping lower bound:  [42 13  0 28 59  0 96 98 59 89 48 47 83  0 12]


# Compare np.clip() vs manual np.where() clipping - implement the same clipping using both and verify the outputs match.

In [25]:
demo=np.random.randint(-20,50,25)
where_clipping=np.where(demo<0,0,np.where(demo>10,10,demo))
clip_clipping=np.clip(demo,0,10)
print("Orginal data: \n",demo)
print("Clipped using where: \n",where_clipping)
print("Clipped using clip:\n",clip_clipping)
print("Are Same?: ",np.array_equal(where_clipping,clip_clipping))

Orginal data: 
 [-15  25  16  14  20   5  29  33  17  45  13  47  12  25  -7  48   8 -10
  37 -19  -8  28  31  49 -20]
Clipped using where: 
 [ 0 10 10 10 10  5 10 10 10 10 10 10 10 10  0 10  8  0 10  0  0 10 10 10
  0]
Clipped using clip:
 [ 0 10 10 10 10  5 10 10 10 10 10 10 10 10  0 10  8  0 10  0  0 10 10 10
  0]
Are Same?:  True
