# Random Arrays(np.random())

In [ ]:
# Generate 10 random values between 0 and 1.
import numpy as np 
rnd=np.random.rand(10)  # random.rand(n) function generates n floats in the range[0,1]
print(rnd)


[0.29168692 0.98097282 0.39617595 0.9754623  0.08533285 0.77097209
 0.52615294 0.33039326 0.78523472 0.28303655]


In [6]:
# Generate a 3 x 3 matrix of random values.
rnd=np.random.rand(3,3)
print(rnd)

[[0.08313154 0.67705365 0.76667509]
 [0.94801089 0.53671964 0.2685102 ]
 [0.20077073 0.26623926 0.63800853]]


In [7]:
# Generate 20 random integers between 1 and 100.
rndint=np.random.randint(1,10,size=20)
print(rndint)

[1 9 5 3 4 4 7 4 9 5 1 3 4 2 2 6 6 8 1 6]


In [9]:
# Generate 4 x 5 matrix of random integers between 10 and 50.
rndmat=np.random.randint(10,50,size=(4,5))
print(rndmat)

[[19 18 43 20 41]
 [23 10 40 34 36]
 [46 44 15 17 24]
 [18 34 11 49 30]]


In [16]:
# Generate a random array using a fixed seed and verfiy that the same output is produced repeatedly.
np.random.seed(43)
randonArr=np.random.rand(10)
print(randonArr)

np.random.seed(43)
randomArr=np.random.rand(10)
print(randomArr)

print(np.array_equal(randonArr,randomArr))

[0.11505457 0.60906654 0.13339096 0.24058962 0.32713906 0.85913749
 0.66609021 0.54116221 0.02901382 0.7337483 ]
[0.11505457 0.60906654 0.13339096 0.24058962 0.32713906 0.85913749
 0.66609021 0.54116221 0.02901382 0.7337483 ]
True


In [19]:
# Generate 100 random number and find their mean.
nums=np.random.randint(1,100,size=100)
print(nums.sum())

4837


In [21]:
# Generate a 5 x 5 matrix of random integers and find the maximum and minimum values.
mat=np.random.randint(1,9,size=(5,5))
matMax=mat.max()
matMin=mat.min()
print(mat)
print("Maximum: ",matMax)
print("Minimun: ",matMin)

[[4 6 2 5 1]
 [1 3 1 2 1]
 [2 7 1 7 3]
 [2 6 2 8 2]
 [2 1 6 7 6]]
Maximum:  8
Minimun:  1


In [22]:
# Generate 50 random integers and count how many are greater than 75.
randint=np.random.randint(0,101,50)
print("Random Integers: ",randint)

count=np.sum(randint>75)
print("Count greater than 75: ",count)

Random Integers:  [ 9 24  2 48 61 77 37  5  0 81 99 76 75 90 21 66 95 32 43 10 47  7 27 73
  8 81 40  5 36 81 97 27 11 40 26 48 65 33 28 90 99 56  3 40 13 23 42 98
 47 23]
Count greater than 75:  12
