# Challenge Questions

In [1]:
import numpy as np 

In [11]:
# Create a 6x6 matrix and extract its center 2x2 block.
org_matrix=np.arange(1,37,1).reshape(6,6)
print(org_matrix)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [3]:
sub_matrix=org_matrix[2:4,2:4]
print(sub_matrix)

[[15 16]
 [21 22]]


In [6]:
# Reverse only the rows of a matrix.
rev_row_mat=org_matrix[::-1,:]
print(rev_row_mat)

[[31 32 33 34 35 36]
 [25 26 27 28 29 30]
 [19 20 21 22 23 24]
 [13 14 15 16 17 18]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]]


In [7]:
# Extract all elements greater than the mean of the array.
print(org_matrix[org_matrix.mean()<org_matrix])

[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36]


In [ ]:
# Using fancy indexing, swap the first and last rows of a matrix.
swap_matrix=org_matrix[[5,1,2,3,4,0],:]
print(swap_matrix)

[[31 32 33 34 35 36]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [ 1  2  3  4  5  6]]


In [25]:
# Extract the border elements of a 5x5.
new_matrix=org_matrix[:5,:5]
print(new_matrix)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]
 [25 26 27 28 29]]


In [26]:
top=new_matrix[0,:]
print(top)

[1 2 3 4 5]


In [28]:
botton=new_matrix[len(new_matrix)-1,:]
print(botton)

[25 26 27 28 29]


In [34]:
left_right=new_matrix[1:len(new_matrix)-1,[0,len(new_matrix)-1]]
print(left_right)

[[ 7 11]
 [13 17]
 [19 23]]


In [ ]:
result=np.concat(top,botton,left_right.flatten())
print(result)

TypeError: only integer scalar arrays can be converted to a scalar index