# Challenge Questions

In [1]:
import numpy as np 

In [70]:
# Create a 6x6 matrix and extract its center 2x2 block.
org_matrix=np.arange(1,37,1).reshape(6,6)
print(org_matrix)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [3]:
sub_matrix=org_matrix[2:4,2:4]
print(sub_matrix)

[[15 16]
 [21 22]]


In [6]:
# Reverse only the rows of a matrix.
rev_row_mat=org_matrix[::-1,:]
print(rev_row_mat)

[[31 32 33 34 35 36]
 [25 26 27 28 29 30]
 [19 20 21 22 23 24]
 [13 14 15 16 17 18]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]]


In [7]:
# Extract all elements greater than the mean of the array.
print(org_matrix[org_matrix.mean()<org_matrix])

[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36]


In [ ]:
# Using fancy indexing, swap the first and last rows of a matrix.
swap_matrix=org_matrix[[5,1,2,3,4,0],:]
print(swap_matrix)

[[31 32 33 34 35 36]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [ 1  2  3  4  5  6]]


In [25]:
# Extract the border elements of a 5x5.
new_matrix=org_matrix[:5,:5]
print(new_matrix)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]
 [25 26 27 28 29]]


In [ ]:
top=new_matrix[0,:]
print(top)

[1 2 3 4 5]


In [ ]:
bottom=new_matrix[len(new_matrix)-1,:]
print(bottom)

[25 26 27 28 29]


In [55]:
left=new_matrix[1:len(new_matrix)-1,0]
print(left)

[ 7 13 19]


In [58]:
right=new_matrix[1:len(new_matrix)-1,4]
print(right)

[11 17 23]


In [62]:
border_elements=np.concatenate((top,bottom,left,right))
print(border_elements)

[ 1  2  3  4  5 25 26 27 28 29  7 13 19 11 17 23]


In [64]:
# Extract the diagonal and anti-diagonal of a matrix.
dia_ele=org_matrix[[0,1,2,3,4,5],[0,1,2,3,4,5]]
print(dia_ele)

[ 1  8 15 22 29 36]


In [66]:
anti_dia_ele=org_matrix[[0,1,2,3,4,5],[5,4,3,2,1,0]]
print(anti_dia_ele)

[ 6 11 16 21 26 31]


In [71]:
# Replace all odd values with zero
org_matrix[org_matrix%2 !=0]=0
print(org_matrix)

[[ 0  2  0  4  0  6]
 [ 0  8  0 10  0 12]
 [ 0 14  0 16  0 18]
 [ 0 20  0 22  0 24]
 [ 0 26  0 28  0 30]
 [ 0 32  0 34  0 36]]
