# identity() & eye()

In [1]:
# Create a 3 x 3 identity matrix.
import numpy as np 
mat=np.identity(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
# Create a 5 x 5 identity matrix.
mat5=np.identity(5)
print(mat5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
# Create a 4 x 4 matrix using eye().
eye4=np.eye(4)
print(eye4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
# Create a 4 x 5 matrix using eye().
mat45=np.eye(4,5)
print(mat45)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
# Create a matrix with ones on the first upper dialognal using eye().
upr=np.eye(3,k=1)
print(upr)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [7]:
# Create a matrix with ones on the first lower dialognal using eye().
lwr=np.eye(3,k=-1)
print(lwr)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
# Create a 6 x 6 identity matrix and find its trace.
mtr=np.identity(6)
print(mtr.trace()) # trace is the sum of elements in main diagonal

6.0
