#flatten()

In [1]:
import numpy as np 
arr=np.arange(1,17).reshape(4,4)
print("Array is: \n",arr)

Array is: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
# Flatten the array and find the sum of the last 5 elements.
flatten_arr=arr.flatten()
print("The sum of the last 5 elements after flatten: ",flatten_arr[-5:].sum())

The sum of the last 5 elements after flatten:  70


In [5]:
# Flatten the array and extract elements from position 5 to 10.
print("Elements from position 5 to 10 in flatten array are: ",flatten_arr[4:10])

Elements from position 5 to 10 in flatten array are:  [ 5  6  7  8  9 10]


In [6]:
# Flatten the array and find the difference between the largest and smallest element.
print("Difference between largest and smallest element is ",flatten_arr.max()-flatten_arr.min())

Difference between largest and smallest element is  15


# Next Module

In [7]:
arr=np.random.randint(10,90,25).reshape(5,5)
print("The Array is : \n",arr)

The Array is : 
 [[28 69 82 38 18]
 [12 45 47 39 82]
 [85 88 18 65 38]
 [44 77 66 27 81]
 [37 60 51 38 72]]


In [10]:
# Flatten the array and calculate the sum of elements at even indices.
flatten_arr=arr.flatten()
evenIdxEle=flatten_arr[::2]
print("Sum of elements at even index: ",evenIdxEle.sum())

Sum of elements at even index:  617


In [ ]:
# find the product of the first 10 elements.
first_ten=flatten_arr[:10]
print("First ten elements: ",first_ten)
print("Product of first then elements: ",np.prod(first_ten))

First ten elements:  [28 69 82 38 18 12 45 47 39 82]
Product of first then elements:  8795229035523840


In [16]:
# Determine how many elements are divisible by both 2 and 3.
mask=(flatten_arr%2==0)&(flatten_arr%3==0)
divisible_elements=flatten_arr[mask]
print("Divisible elements: ",divisible_elements)
print("Count: ",divisible_elements.size)


Divisible elements:  [18 12 18 66 60 72]
Count:  6


# Next Module

In [22]:
sales=np.random.randint(100,500,9).reshape(3,3)
print("Sales Record: \n",sales)

Sales Record: 
 [[263 131 461]
 [495 346 498]
 [204 226 232]]


In [23]:
flatten_arr=sales.flatten()
# Find the top 3 sales values.
top_values=3
sorted_arr=np.sort(flatten_arr)
print(f"Top {top_values} sales values are :",sorted_arr[-top_values:])

Top 3 sales values are : [461 495 498]


In [24]:
# Find the average of all sales.
print("Average: ",np.round(flatten_arr.mean(),2))

Average:  317.33


In [26]:
# Count sales greater then 140.
great_sales=flatten_arr[flatten_arr>140]
print("Sales greater than 140: ",great_sales)
print("Sales count greater than 140: ",great_sales.size)

Sales greater than 140:  [263 461 495 346 498 204 226 232]
Sales count greater than 140:  8
