# Generate 50 random salaries between 20 to 200k. Find P25, P50, P75. What percentage of values fall between P25 and P75? Verify by counting.

In [18]:
import numpy as np 
salaries=np.random.randint(20,200,50)
P1=np.percentile(salaries,25)
P2=np.percentile(salaries,50)
P3=np.percentile(salaries,75)
print("25th Percentile(P1): ",P1)
print("50th Percentile(P2): ",P2)
print("75th Percentile(P3): ",P3)

25th Percentile(P1):  68.5
50th Percentile(P2):  103.5
75th Percentile(P3):  139.0


In [19]:
print("Salaries: ",salaries)
# Count values between P25 and P75
mask=(salaries>=P1)&(salaries<=P3)
count=np.sum(mask)
print("Count: ",count)

percentage=(count/50)*100
print(f"Percentage of values between P25 & P75: {percentage}%")

Salaries:  [149 194  77  80  98 192 122 178 140 196  48 165  32 191  56 122  34 115
  41  47  95 119 136 145  47  70  68 126 199 158 133 127  72 125  98  73
  94  23 133  23  99 187  90 133 161 100  64  58 107  29]
Count:  24
Percentage of values between P25 & P75: 48.0%


# Given a 2D array, find the 75th percentile of each column using the axis argument.

In [4]:
import numpy as np 
arr=np.random.randint(10,100,25).reshape(5,5)
print("The 2D Array: \n",arr)

The 2D Array: 
 [[35 54 25 84 80]
 [96 11 88 70 85]
 [65 30 10 65 77]
 [65 94 95 62 70]
 [51 33 15 92 33]]


In [12]:
P75=np.percentile(arr,75,axis=1)
print("The 75th percentile per column: ",P75)

The 75th percentile per column:  [80. 88. 65. 94. 51.]


Meaning: 80%, 88%, 65%, 94% & 51% student of column1, column2, column3, column4 and column5 have scored less than 75% percent of marks.

# What's the difference between np.percentile(arr,50) and np.median(arr)? Verify they give the same result, then check if there any edge case where they might differ?

In [14]:
arr=np.random.randint(10,150,25)
print("Array: ",arr)

Array:  [ 71  57 116  95 136  30  25  90 148 137 102 145  87 132  91  53  60  87
  94  87  11 124  47  96  86]


In [16]:
print("Result from Percentile(P50): ",np.percentile(arr,50))
print("Result from median: ",np.median(arr))

Result from Percentile(P50):  90.0
Result from median:  90.0


Edge Cases:
 i.   Even-sized dataset with different interpolation methods
 ii.  Nan values.
 iii. Axis handling (on older version)

In [ ]:
# i
import numpy as np 
data=[1,2,3,4]
print("np.median(): ",np.median(data)) # Always average of middle two

print("np.percentile (linear): ",np.percentile(data,50,method='linear')) # default
print("np.percentile (nearest): ",np.percentile(data,50,method='nearest'))
print("np.percentile (lower): ",np.percentile(data,50,method='lower'))
print("np.percentile (higher): ",np.percentile(data,50,method='higher'))
print("np.percentile (midpoint): ",np.percentile(data,50,method='midpoint'))  # average

np.median():  2.5
np.percentile (linear):  2.5
np.percentile (nearest):  3
np.percentile (lower):  2
np.percentile (higher):  3
np.percentile (midpoint):  2.5


In [19]:
# ii
data=[1,2,np.nan,4]
print("np.median: ",np.median(data)) # returns nan
print("np.nanmedian: ",np.nanmedian(data)) # Ignores NaN 
print("np.percentile: ",np.percentile(data,50)) # returns nan

np.median:  nan
np.nanmedian:  2.0
np.percentile:  nan


In [ ]:
# iii. (Identical in numpy version >=1.22)
arr=np.array([[1,2],[3,4]])
print("np.median axis=0: ",np.median(arr,axis=0))
print("np.percentile axis=0: ",np.percentile(arr,50,axis=0))

np.median axis=0:  [2. 3.]
np.percentile axis=0:  [2. 3.]


# Using IQR, write a function remove_outliers(arr) that returns the array with outliers replaced by np.nan. 

In [30]:
def remove_outliers(arr):
    q1=np.percentile(arr,25)
    q3=np.percentile(arr,75)
    iqr=q3-q1

    lower_bound=q1-1.5*iqr
    upper_bound=q3+1.5*iqr

    arr_out=np.where((arr<lower_bound) | (arr>upper_bound),np.nan,arr)
    return arr_out

data=np.array([10,5,16,32,90,-100,300,40])
print("Orginal data: ",data)
print("Masked data: ",remove_outliers(data))

Orginal data:  [  10    5   16   32   90 -100  300   40]
Masked data:  [10.  5. 16. 32. 90. nan nan 40.]
