# An array of empoyees salaries:

In [ ]:
import numpy as np 
salaries=np.array([45000,52000,61000,38000,70000,48000],dtype=float)

Sliced first 4 Salaries:  [45000. 52000. 61000. 38000.]
Sliced raise salaries:  [49500. 57200. 67100. 41800.]
Orginal Salaries:  [49500. 57200. 67100. 41800. 70000. 48000.]


In [19]:
# A colleague slices the salaries to get first 4 Salaries.
salaries4=salaries[:4]
print("Sliced first 4 Salaries: ",salaries4)

Sliced first 4 Salaries:  [49500. 57200. 67100. 41800.]


In [20]:
# Everyone in the slice get 10% raise
salaries4*=1.1
print("Sliced raise salaries: ",salaries4)

Sliced raise salaries:  [54450. 62920. 73810. 45980.]


In [ ]:
# Will the original salaries array reflect reflect this change?
print("Orginal Salaries: ",salaries) # Affected

Orginal Salaries:  [54450. 62920. 73810. 45980. 70000. 48000.]


In [22]:
# Fix it so the orgiginal is not affected.
salaries=np.array([45000,52000,61000,38000,70000,48000],dtype=float)
salaries4=salaries[:4].copy()
salaries4*=1.1
print("Raised Salaries: ",salaries4)
print("Orginal Salaries: ",salaries)


Raised Salaries:  [49500. 57200. 67100. 41800.]
Orginal Salaries:  [45000. 52000. 61000. 38000. 70000. 48000.]


# A 2D array

In [23]:
data = np.arange(1, 13).reshape(3, 4)

In [24]:
# Take the transpose of data and assign it to t.
t=np.transpose(data)
print("Orginal data: \n",data)
print("Assigned Transpose data: \n",t)

Orginal data: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Assigned Transpose data: 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
# Modify some element in t and check whether data was affected.
t[0,0]=100
t[1,1]=200
print("Transposed data after modification: \n",t)
print("Original data: \n",data)

Transposed data after modification: 
 [[100   5   9]
 [  2 200  10]
 [  3   7  11]
 [  4   8  12]]
Original data: 
 [[100   2   3   4]
 [  5 200   7   8]
 [  9  10  11  12]]


Both original data is also affected because we assigned t the transpose value of data
 so t referenced to data when we modified.

# Two Variables pointing to the same array

In [30]:
a = np.array([10, 20, 30, 40, 50])
b = a
c = a.copy()
print(np.shares_memory(a,b))
print(np.shares_memory(a,c))

True
False


# A dataset of 6 products with their stock quantities:

In [31]:
inventory = np.array([
    [101, 340],
    [102,  85],
    [103, 512],
    [104,  20],
    [105, 178],
    [106,  95]
])

In [38]:
# Split it into halves
half1,half2=np.vsplit(inventory,2)
print("First half products: \n",half1)
print("Second half products: \n",half2)

First half products: 
 [[  2 340]
 [102  85]
 [103 512]]
Second half products: 
 [[104  20]
 [105 178]
 [106  95]]


In [39]:
# From the bottom half, create a view by slicing only the quantity column.
view=half2[:,1]
print("View: \n", view)

View: 
 [ 20 178  95]


In [40]:
# Set all quantities below 100 to 0 using Boolean indexing on that view.
view[view<100]=0
print("The view: \n",view)

The view: 
 [  0 178   0]


In [ ]:
# Check if the original inventory was modified.
print("Inventory data: \n",inventory) # yes

Inventory data: 
 [[  2 340]
 [102  85]
 [103 512]
 [104   0]
 [105 178]
 [106   0]]


# You have weekly temperature data:

In [ ]:
temps = np.array([
    [28, 30, 32, 31, 29, 27, 33],
    [35, 36, 34, 33, 31, 30, 32],
    [22, 24, 26, 25, 23, 21, 20],
    [30, 31, 29, 28, 27, 26, 25]
])

In [43]:
# Reshape temps into shape (2,2,7) and assign to reshaped.
reshaped=np.reshape(temps,(2,2,7))
print("Reshaped temps:\n",reshaped) 

Reshaped temps:
 [[[28 30 32 31 29 27 33]
  [35 36 34 33 31 30 32]]

 [[22 24 26 25 23 21 20]
  [30 31 29 28 27 26 25]]]


In [44]:
# Confirm whether reshpaed is a view of temps.
print("Is reshaped a view of temps?: ",view.base is None)


Is reshaped a view of temps?:  False


In [45]:
# Modify reshaped
reshaped[0,0,0]=99
print(reshaped)

[[[99 30 32 31 29 27 33]
  [35 36 34 33 31 30 32]]

 [[22 24 26 25 23 21 20]
  [30 31 29 28 27 26 25]]]


In [ ]:
# Compute the max temperature per week on the original temps.
max_temp=reshaped.max(axis=1)
print("Result:\n",max_temp) # first day of first week modified

Result:
 [[99 36 34 33 31 30 33]
 [30 31 29 28 27 26 25]]
