# Indexing 2D Arrays

In [1]:
import numpy as np 
rows=4
cols=4
matrix=np.array([[10*(i+1) + j+1 for j in range(cols)]for i in range(rows)])
print(matrix)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [2]:
# Access element 22
print(matrix[1][1])

22


In [ ]:
# Access element 34.
print(matrix[2][3]) # or matrix[2,3]

34


In [4]:
# Access element 41. 
print(matrix[3][0])

41


In [5]:
# Access the last elemement.
print(matrix[-1][-1])

44


In [ ]:
# Access the entire second row.
second_row=matrix[1] 
print(matrix[1:2,:]) # 2D vector
print(second_row) # 1D array

[[21 22 23 24]]
[21 22 23 24]


In [ ]:
# Access the entire third column.
third_col=matrix[:,2]
print(third_col)

33


In [15]:
# Find the sum of the diagonal elements.
dia_sum=np.trace(matrix)
print(dia_sum)

110


In [16]:
# Replace 33 with 100
matrix[2,2]=100
print(matrix)

[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32 100  34]
 [ 41  42  43  44]]


In [17]:
# Access element 24 using negative indexing.
print(matrix[-3,-1])

24
