# Concatenate

In [1]:
import numpy as np 
a=np.array([10,20,30,40])
b=np.array([50,60,70,80])

Create a single array containing all values and determine:

In [ ]:
c=np.concatenate([a,b])
print(f"Combined Array: ",c)

Combined Array:  [10 20 30 40 50 60 70 80]


In [ ]:
# 1. Sum of elements at odd indices.
elements_at_oddIdx=c[1::2]
print("Elements are odd indices: ",elements_at_oddIdx)
print("Sum of elements at odd indices: ",elements_at_oddIdx.sum())

Elements are odd indices:  [20 40 60 80]
Sum of elements at odd indices:  200


In [ ]:
# 2. Average of the first four elements.
ele4=c[:4]
print("First four elements are: ",ele4)
print("Average of first four elements are: ",ele4.mean())

First four elements are:  [10 20 30 40]
Average of first four elements are:  25.0


In [7]:
# Difference between largest and smallest value.
largest=c.max()
smallest=c.min()
print(f"The largest value is {largest} and smallest value is {smallest} with difference of {largest-smallest} ")

The largest value is 80 and smallest value is 10 with difference of 70 


# Multi-Array Concatenation with different shapes.

A company has monthly expense data from 3 departments:
  * Department A(deptA) expenses(Jan-Mar): [[1000,1500],[1200,1600],[1100,1550]](3months x 2 categories)
  * Department B(deptB) expenses(Jan-Mar): [[900,1400],[950,1450],[1000,1500]](3months x 2 categories)
  * Department B(deptB) expenses(Jan-Mar): [[1100,1600],[1300,1700],[1200,1650]](3months x 2 categories)

In [22]:
deptA=np.array([[1000,1500],[1200,1600],[1100,1550]])
deptB=np.array([[900,1400],[950,1450],[1575,1500]])
deptC=np.array([[1100,1600],[1300,1700],[1200,1650]])
# Conatenate all three along axis=0 to create a single array showing all departments' expenses.
dept=np.concatenate([deptA,deptB,deptC],axis=0)
print("Resulting monthly expense data from 3 departments: \n",dept)

Resulting monthly expense data from 3 departments: 
 [[1000 1500]
 [1200 1600]
 [1100 1550]
 [ 900 1400]
 [ 950 1450]
 [1575 1500]
 [1100 1600]
 [1300 1700]
 [1200 1650]]


In [25]:
# 1D array of 13 monthly sales figures: 
sales = np.array([500, 430, 610, 720, 680, 540, 490, 770, 630, 580, 540, 650])
# split it so eacch quarter is a separate arry.
quarter_sales=np.split(sales,4)
qtr1,qtr2,qtr3,qtr4=quarter_sales
print("Sales of first three month: ",qtr1)
print("Sales of  second quarter month: ",qtr2)
print("Sales of third quarter month: ",qtr3)
print("Sales of last three month: ",qtr4)

Sales of first three month:  [500 430 610]
Sales of  second quarter month:  [720 680 540]
Sales of third quarter month:  [490 770 630]
Sales of last three month:  [580 540 650]


In [26]:
# Find  which quareter had the highest total sales.
sums=[int(p.sum()) for p in quarter_sales]
print("Total Sales per Quarter: ",sums)
print(f"Quarter {np.argmax(sums)+1} has highest total sales which is {max(sums)}$")


Total Sales per Quarter:  [1540, 1940, 1890, 1770]
Quarter 2 has highest total sales which is 1940$


In [31]:
# 2D arrays representing product ratings from two different stores(rows=products,cols=rating categories)
store_a = np.array([[4, 5, 3], [3, 4, 5], [5, 3, 4]])
store_b = np.array([[3, 4, 5], [5, 5, 3], [4, 3, 5]])

# Stack them so the result has 6 rows(all products from both stores one after another)
stores=np.vstack([store_a,store_b])
print("Product X Ratings: \n",stores)

# Split the result back into two equal halves and verify the second half matches 
first,second=np.vsplit(stores,2)
print("Result: ",np.array_equal(store_b,second))

Product X Ratings: 
 [[4 5 3]
 [3 4 5]
 [5 3 4]
 [3 4 5]
 [5 5 3]
 [4 3 5]]
Result:  True
